<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Finkelstein, Taubman, Wright, Bernstein, Gruber, Newhouse, Allen, Baicker">
<meta name="dcterms.date" content="2012-01-01">
<meta name="description" content="IV using Oregon Medicaid lottery as instrument for insurance coverage — DoubleML PLIV extension">

<title>Oregon Health Insurance Experiment (DoubleML) – RECAST</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e57afe155632aaa660b5c675715ddaef.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">RECAST</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../papers.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../submissions.html"> 
<span class="menu-text">Tracker</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../submit.html"> 
<span class="menu-text">Submit</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../framework.html"> 
<span class="menu-text">Framework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/qgallea/recast-causal-ai"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#paper-summary" id="toc-paper-summary" class="nav-link active" data-scroll-target="#paper-summary">Paper summary</a></li>
  <li><a href="#replication-results" id="toc-replication-results" class="nav-link" data-scroll-target="#replication-results">Replication results</a></li>
  <li><a href="#dml-extension" id="toc-dml-extension" class="nav-link" data-scroll-target="#dml-extension">DML Extension</a></li>
  <li><a href="#gate-analysis" id="toc-gate-analysis" class="nav-link" data-scroll-target="#gate-analysis">GATE Analysis</a></li>
  <li><a href="#pedagogical-assessment" id="toc-pedagogical-assessment" class="nav-link" data-scroll-target="#pedagogical-assessment">Pedagogical assessment</a></li>
  <li><a href="#referee-reports" id="toc-referee-reports" class="nav-link" data-scroll-target="#referee-reports">Referee reports</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Oregon Health Insurance Experiment (DoubleML)</h1>
  <div class="quarto-categories">
    <div class="quarto-category">IV</div>
    <div class="quarto-category">Health</div>
    <div class="quarto-category">2012</div>
    <div class="quarto-category">PASS</div>
    <div class="quarto-category">DoubleML</div>
  </div>
  </div>

<div>
  <div class="description">
    IV using Oregon Medicaid lottery as instrument for insurance coverage — DoubleML PLIV extension
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Finkelstein, Taubman, Wright, Bernstein, Gruber, Newhouse, Allen, Baicker </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2012</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<div class="construction-banner">
<p>🚧 <strong>Under construction &amp; testing</strong> — This site is in active development. Results have not been independently verified. Do not cite or rely on any output without manual review.</p>
</div>
<section id="paper-summary" class="level2">
<h2 class="anchored" data-anchor-id="paper-summary">Paper summary</h2>
<p><strong>Citation:</strong> Finkelstein, A., Taubman, S., Wright, B., Bernstein, M., Gruber, J., Newhouse, J.P., Allen, H., &amp; Baicker, K. (2012). The Oregon Health Insurance Experiment: Evidence from the First Year. <em>Quarterly Journal of Economics</em>, 127(3), 1057–1106. <a href="https://doi.org/10.1093/qje/qjs020">DOI</a></p>
<p><strong>Identification strategy:</strong> In 2008, Oregon held a lottery to allow uninsured low-income adults to apply for Medicaid. Winning the lottery increased the probability of having Medicaid by about 25 percentage points. The paper uses lottery selection as an instrument for actual Medicaid enrollment in a 2SLS framework to estimate the LATE of insurance coverage on self-reported health. Standard errors are clustered at the household level; regressions include draw-wave x household-size fixed effects and survey response weights.</p>
<p><strong>Key original result:</strong> The IV/LATE estimate of the effect of Medicaid enrollment on self-reported good health is <strong>0.133</strong> (SE 0.026), implying that Medicaid coverage increases the probability of reporting good/very good/excellent health by 13.3 percentage points among compliers.</p>
<hr>
</section>
<section id="replication-results" class="level2">
<h2 class="anchored" data-anchor-id="replication-results">Replication results</h2>
<p>The replication <strong>passed</strong>. Maximum coefficient deviation from the published table: <strong>1.28%</strong>. All three specifications match the original within 1.3%.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Specification</th>
<th>Original</th>
<th>Replicated</th>
<th>Delta (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>IV/LATE (Table 9)</td>
<td>0.133 (0.026)</td>
<td>0.132 (0.026)</td>
<td>0.61%</td>
</tr>
<tr class="even">
<td>ITT reduced form (Table 9)</td>
<td>0.039 (0.008)</td>
<td>0.039 (0.008)</td>
<td>0.78%</td>
</tr>
<tr class="odd">
<td>First stage (Table 3)</td>
<td>0.289 (0.007)</td>
<td>0.293 (0.007)</td>
<td>1.28%</td>
</tr>
</tbody>
</table>
<p><em>Note: Replication sample contains 23,361 observations vs.&nbsp;the published 23,741 (1.6% difference, likely due to missing covariate values in the merge).</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forest_plot.png" class="img-fluid figure-img" alt="Forest plot showing coefficient estimates and 95% confidence intervals for published IV/LATE, replicated IV, and two DML learners (RandomForest and LassoCV). DML estimates cluster near 0.165 with confidence intervals overlapping the published IV."></p>
<figcaption>Forest plot: Published IV, Replicated IV, and DML estimates</figcaption>
</figure>
</div>
<hr>
</section>
<section id="dml-extension" class="level2">
<h2 class="anchored" data-anchor-id="dml-extension">DML Extension</h2>
<p>The <strong>Partially Linear IV (PLIV)</strong> model from DoubleML was applied with 5-fold cross-fitting and 3 repetitions, using lottery selection as the instrument and draw-wave x household-size dummies as controls.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Learner</th>
<th>Estimate</th>
<th>SE</th>
<th>95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LassoCV</strong></td>
<td><strong>0.165</strong></td>
<td><strong>0.023</strong></td>
<td><strong>[0.120, 0.209]</strong></td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td>0.164</td>
<td>0.023</td>
<td>[0.119, 0.208]</td>
</tr>
</tbody>
</table>
<p><strong>Both learners agree closely</strong> (difference &lt; 0.001), confirming the result is robust to learner choice.</p>
<p><strong>Interpretation:</strong> The DML-PLIV estimate (0.165, 95% CI [0.120, 0.209]) is approximately 24% larger in magnitude than the published IV/LATE (0.133). The published coefficient falls well inside the DML 95% CI, confirming statistical compatibility. The DML standard error (0.023) is slightly smaller than the published SE (0.026), reflecting marginally more precise estimation. The DML-PLIV targets the same LATE estimand as the original 2SLS.</p>
<p><strong>Nuisance model performance:</strong> The nuisance R-squared is very low – outcome R-squared is 0.004 and treatment R-squared is -0.28 (worse than predicting the mean). This is expected by design: in a well-conducted randomized lottery, treatment assignment is independent of covariates, so no ML model should be able to predict treatment. The DML Neyman-orthogonal score is robust to poor nuisance estimation, so this does not invalidate the results.</p>
<hr>
</section>
<section id="gate-analysis" class="level2">
<h2 class="anchored" data-anchor-id="gate-analysis">GATE Analysis</h2>
<p>GATEs were computed by fitting separate PLIV models on each household-size subgroup (the native <code>.gate()</code> method is not available for PLIV).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th>N</th>
<th>Estimate</th>
<th>SE</th>
<th>95% CI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>numhh = 1</td>
<td>16,395</td>
<td>0.144</td>
<td>0.024</td>
<td>[0.096, 0.191]</td>
</tr>
<tr class="even">
<td>numhh = 2</td>
<td>6,909</td>
<td>0.252</td>
<td>0.059</td>
<td>[0.137, 0.367]</td>
</tr>
<tr class="odd">
<td>numhh = 3</td>
<td>57</td>
<td>-1.336</td>
<td>0.318</td>
<td>[-1.960, -0.713]</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="gate_plot.png" class="img-fluid figure-img" alt="GATE plot showing DML treatment effect estimates by household size. Single-person and two-person households show positive effects; the tiny three-person group (N=57) shows an implausible negative estimate."></p>
<figcaption>GATE plot by household size</figcaption>
</figure>
</div>
<p>There is suggestive evidence that two-person households benefit more from Medicaid (0.252) than single-person households (0.144), but the confidence intervals overlap. The numhh=3 estimate (N=57) is unreliable due to the tiny subgroup size and should be disregarded. These are pointwise CIs (not jointly valid confidence bands).</p>
<hr>
</section>
<section id="pedagogical-assessment" class="level2">
<h2 class="anchored" data-anchor-id="pedagogical-assessment">Pedagogical assessment</h2>
<p>DML confirms and slightly strengthens the original IV estimate (0.165 vs 0.133). Both Random Forest and Lasso learners agree to within 0.001. The published coefficient falls inside the DML confidence interval, confirming consistency. However, the nuisance R-squared is very low – expected for a randomized experiment where covariates should not predict treatment. This means DML’s flexible first stage adds little because the first stage is already well-specified by design.</p>
<p><strong>Verdict:</strong> DML confirms robustness but adds modest value in a well-randomized setting. The real value is methodological – demonstrating that the original result survives flexible ML-based estimation of nuisance parameters. The near-identical performance of both learners is itself informative: it shows that in a clean experiment, the parametric and nonparametric approaches converge, as theory predicts. Survey weights (used in the original but not in DML) may account for part of the 24% magnitude difference.</p>
<hr>
</section>
<section id="referee-reports" class="level2">
<h2 class="anchored" data-anchor-id="referee-reports">Referee reports</h2>
<p><strong>Referee consensus:</strong> The RECAST is ready for publication. The replication is excellent (all specs within 1.3%), the DML-PLIV extension is methodologically sound, and all 13 issues from Round 1 – including LATE estimand clarification, nuisance FAIL contextualisation, GATE CI relabelling, and magnitude difference discussion – were resolved. No blocking or major issues remain.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Identification</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Referee 1 Report: Identification</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">DML Methods</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Referee 2 Report: DML Methods &amp; Causal Forest</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href="">Robustness</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false" href="">Referee 3 Report: Robustness and Replication</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-7-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-7" role="tab" aria-controls="tabset-1-7" aria-selected="false" href="">Synthesis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-8-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-8" role="tab" aria-controls="tabset-1-8" aria-selected="false" href="">Synthesis Report – Round 1</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-9-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-9" role="tab" aria-controls="tabset-1-9" aria-selected="false" href="">Final Report</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-10-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-10" role="tab" aria-controls="tabset-1-10" aria-selected="false" href="">Overall Assessment</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-11-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-11" role="tab" aria-controls="tabset-1-11" aria-selected="false" href="">What Was Solved During Revision</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-12-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-12" role="tab" aria-controls="tabset-1-12" aria-selected="false" href="">Remaining Issues</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-13-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-13" role="tab" aria-controls="tabset-1-13" aria-selected="false" href="">Key Results</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-14-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-14" role="tab" aria-controls="tabset-1-14" aria-selected="false" href="">Notes for the Reader</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">

</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor concerns</p>
<section id="blocking-issues-re-analysis-required" class="level3">
<h3 class="anchored" data-anchor-id="blocking-issues-re-analysis-required">Blocking issues (re-analysis required)</h3>
<ul>
<li>None</li>
</ul>
</section>
<section id="major-issues-prosetable-edits-required" class="level3">
<h3 class="anchored" data-anchor-id="major-issues-prosetable-edits-required">Major issues (prose/table edits required)</h3>
<ul>
<li><strong>M1: Estimand inconsistency between paper text and DML section.</strong> The introduction (Section 1) correctly states the estimand is the LATE. However, the DML extension section (Section 3) does not explicitly restate that the PLIV model targets the same LATE estimand. The paper should clarify that the PLIV model preserves the IV-based LATE interpretation, not an ATE. This is important because LATE and ATE coincide only under homogeneous treatment effects, and the GATE analysis in Section 3.3 suggests heterogeneity. A sentence clarifying that the DML-PLIV estimate is also a LATE (among compliers with the lottery instrument) would resolve this.</li>
</ul>
</section>
<section id="minor-issues" class="level3">
<h3 class="anchored" data-anchor-id="minor-issues">Minor issues</h3>
<ul>
<li><strong>m1: First-stage F-statistic not reported for DML.</strong> The paper reports F &gt;&gt; 500 for the original 2SLS first stage (Section 2.1) but does not report any first-stage diagnostics for the DML-PLIV model. While the DML framework handles weak instruments differently (through the Neyman-orthogonal score), the paper should note that the instrument remains strong in the DML context, or explain why a separate F-statistic is not applicable.</li>
<li><strong>m2: Sample size discrepancy between published paper and DML.</strong> The published paper reports N=23,741 (paper_spec.json) but the DML analysis uses N=23,361 (dml_results.json). The difference of 380 observations (1.6%) is likely due to missing values in covariates used by the DML model. This should be explicitly acknowledged in the text with a brief explanation.</li>
<li><strong>m3: GATE interpretation overstates heterogeneity finding.</strong> Section 3.3 states “the results suggest meaningful heterogeneity” but the heterogeneity is driven entirely by the numhh=3 group (N=57), which the paper itself acknowledges is unreliable. Between numhh=1 (0.144) and numhh=2 (0.252), the confidence intervals overlap ([0.096, 0.191] vs [0.137, 0.367]). The paper should state more carefully that the heterogeneity finding is not robust and is driven by an implausibly small subgroup.</li>
</ul>
</section>
<section id="comments-to-the-authors" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors">Comments to the authors</h3>
<p>The identification strategy is well-described and faithful to the original paper. The Oregon lottery provides one of the cleanest natural experiments in health economics, and the paper correctly identifies the LATE as the target estimand with lottery selection as the instrument for Medicaid enrollment. The first-stage strength (F &gt;&gt; 500) is exceptional and eliminates weak instrument concerns.</p>
<p>The DML-PLIV model is the correct choice for extending an IV design. The paper does a good job explaining why the Neyman-orthogonal score makes the DML estimates robust to poor nuisance model fit (Section 4), which is critical given the near-zero nuisance R-squared values. However, the paper should be more explicit that the DML-PLIV model targets the same LATE as the original 2SLS – this is not merely a technical point, but affects how the 24.1% magnitude difference between the DML and published estimates should be interpreted.</p>
<p>The GATE analysis is a useful addition but the interpretation needs tightening. The only economically meaningful heterogeneity comparison is between numhh=1 and numhh=2, and those estimates have overlapping confidence intervals. The numhh=3 result is correctly flagged as unreliable, but the section’s opening claim of “meaningful heterogeneity” overstates the evidence. A more accurate framing would be: “we find suggestive evidence that two-person households may benefit more from Medicaid, but we cannot reject equal treatment effects across the numhh=1 and numhh=2 subgroups.”</p>
<p>The sample size discrepancy (23,741 vs 23,361) is minor but should be documented. If the 380 missing observations are due to listwise deletion on covariates, this is standard but should be stated.</p>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">

</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor concerns</p>
<section id="blocking-issues" class="level3">
<h3 class="anchored" data-anchor-id="blocking-issues">Blocking issues</h3>
<ul>
<li>None</li>
</ul>
</section>
<section id="major-issues" class="level3">
<h3 class="anchored" data-anchor-id="major-issues">Major issues</h3>
<ul>
<li><strong>M1: Nuisance R-squared interpretation should distinguish between expected-by-design and problematic cases.</strong> The paper correctly explains that low nuisance R-squared is expected in a randomized experiment (Section 4). However, the diagnostics table labels nuisance_quality as “FAIL” (red) without qualification. The paper text handles this well, but the table presentation creates an inconsistency. The paper should either (a) add a qualifier to the diagnostics table noting this is expected, or (b) add a footnote to the table explaining why FAIL is expected here. Currently a reader scanning the table without reading the text would conclude the analysis failed quality checks.</li>
</ul>
</section>
<section id="minor-issues-1" class="level3">
<h3 class="anchored" data-anchor-id="minor-issues-1">Minor issues</h3>
<ul>
<li><strong>m1: Learner grid is narrow.</strong> Only two learners are used (RandomForest and LassoCV). The DML literature recommends spanning linear, tree-based, and ensemble methods. Adding at least one boosting method (e.g., XGBoost or GradientBoosting) would strengthen the robustness claim. However, given that both current learners produce nearly identical estimates (0.164 vs 0.165), this is unlikely to change the conclusions.</li>
<li><strong>m2: GATE CIs labeled “joint” but computed pointwise.</strong> The GATE table caption and the gate_plot.pdf axis label say “95% joint CI,” but the GATEs were computed by fitting separate PLIV models on each subgroup (hte_results.json: “method”: “GATE_subgroup”). These are pointwise CIs for each subgroup, not jointly valid confidence bands. The label should be corrected to “95% CI (pointwise)” to avoid overclaiming simultaneous coverage.</li>
<li><strong>m3: No causal forest analysis.</strong> The config disables causal forest (<code>causal_forest.enabled: false</code>). This is acceptable for a PLIV design where CausalIVForest would be needed, but the paper should briefly note why causal forest was not used (e.g., “CausalIVForest is not implemented in the current pipeline” or “the categorical nature of the available covariates limits the usefulness of a causal forest approach”).</li>
<li><strong>m4: Preferred learner selection criterion is ad hoc.</strong> The notebook selects LassoCV as preferred when RF r2_outcome &lt; 0.1. This threshold is arbitrary and not grounded in the DML literature. In this case both learners produce essentially identical estimates, so the choice is inconsequential. But the paper should note the selection criterion or simply state that results are robust across learners rather than emphasizing a “preferred” choice.</li>
</ul>
</section>
<section id="comments-to-the-authors-1" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors-1">Comments to the authors</h3>
<p>The DoubleML implementation is methodologically sound. The choice of DoubleMLPLIV is correct for the IV design, and the cross-fitting procedure (K=5, N_rep=3) is adequate for the sample size (min fold size approximately 4,672, well above the K x min_fold_size &gt; 30 threshold). The nuisance models use appropriate learners and the Neyman-orthogonal score ensures robustness to the poor nuisance fit.</p>
<p>The near-zero and negative nuisance R-squared values (outcome: 0.004, treatment: -0.280) are well-explained in the text as a feature of the randomized design rather than a bug. In a well-conducted lottery, treatment assignment is independent of covariates by construction, so the treatment model should perform no better than the unconditional mean. The negative R-squared for the treatment model simply means the ML predictions are worse than predicting the sample mean, which is expected when the covariates carry no information about treatment. The paper’s argument that DML remains valid via the Neyman-orthogonal score is correct – the key theoretical result in Chernozhukov et al.&nbsp;(2018) is that the score is insensitive to nuisance estimation error, including poor nuisance models.</p>
<p>The GATE analysis uses an appropriate workaround for the absence of a native <code>.gate()</code> method in DoubleMLPLIV. However, the confidence intervals from separate subgroup fits are pointwise, not jointly valid. This distinction matters if the reader wants to test the null of no heterogeneity across groups. The current labeling (“joint CI”) should be corrected. The numhh=3 subgroup (N=57) is too small for reliable DML estimation – the minimum recommended fold size for K=5 cross-fitting would be about 11 observations per fold, which is well below any reasonable threshold. The paper correctly flags this but should consider dropping this group from the GATE table entirely, or at minimum adding an explicit warning in the table itself.</p>
</section>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">

</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor concerns</p>
<section id="blocking-issues-1" class="level3">
<h3 class="anchored" data-anchor-id="blocking-issues-1">Blocking issues</h3>
<ul>
<li>None</li>
</ul>
</section>
<section id="major-issues-1" class="level3">
<h3 class="anchored" data-anchor-id="major-issues-1">Major issues</h3>
<ul>
<li><strong>M1: DML coefficient rounding inconsistency.</strong> The paper text (Section 3.2) reports the preferred DML coefficient as 0.165, but dml_results.json shows 0.164849, which rounds to 0.165 at 3 decimal places. The RF coefficient is reported as 0.164 in the text but is 0.163621 in the JSON (rounds to 0.164). These are consistent. However, the paper states the DML estimate is “24.1% larger” than the published IV (Section 3.2), but (0.165 - 0.133)/0.133 = 24.06%, while using the full precision value (0.164849 - 0.133)/0.133 = 23.9%. The diagnostics_flags.json correctly reports 23.9%. The paper should use a consistent percentage – either 23.9% (from the JSON) or “approximately 24%” to avoid false precision.</li>
</ul>
</section>
<section id="minor-issues-2" class="level3">
<h3 class="anchored" data-anchor-id="minor-issues-2">Minor issues</h3>
<ul>
<li><strong>m1: Replication table claims “three key specifications” but the text only discusses one in detail.</strong> Section 2.2 says “All three are successfully replicated” (IV/LATE, ITT, first stage) but only the IV/LATE estimate is discussed in the text with specific numbers. The ITT (0.039, SE=0.008) and first stage (0.289, SE=0.007) results are only in the table. A brief mention of all three in the text would strengthen the replication narrative.</li>
<li><strong>m2: Forest plot visual inspection.</strong> The forest plot correctly shows four rows: Published IV (LATE), Replicated IV, DML (RandomForest), and DML (LassoCV). The published and replicated IV estimates are visually indistinguishable (0.133 vs 0.132), confirming successful replication. The DML estimates are slightly to the right with overlapping CIs, consistent with the text. The plot is accurate and well-formatted. No issues found.</li>
<li><strong>m3: N in published paper vs replication.</strong> The paper_spec.json reports N=23,741 for the published results, but the replication and DML analyses use N=23,361. The replication_check.json reports “pass: true” with worst_rel_diff_pct of 1.28%, suggesting the replication was successful despite the sample size difference. The sample difference should be noted more prominently (currently not mentioned in the text at all).</li>
<li><strong>m4: Missing robustness checks.</strong> The paper does not include any robustness checks beyond learner variation (RF vs Lasso). Standard robustness checks for this setting would include: (a) alternative outcome definitions (e.g., the continuous health measure rather than the binary), (b) excluding the survey weights to check sensitivity, or (c) subsample stability (e.g., by lottery draw wave). While these would require additional notebook runs, the paper should at least acknowledge these as limitations.</li>
</ul>
</section>
<section id="comments-to-the-authors-2" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors-2">Comments to the authors</h3>
<p>The replication is successful and well-documented. The 1.3% maximum relative deviation across three specifications (IV/LATE, ITT, first stage) is excellent and well within acceptable tolerances. The forest plot provides a clear visual summary confirming that the published and replicated estimates are virtually identical, and that the DML extension yields modestly larger but statistically compatible estimates.</p>
<p>The robustness of the DML estimates across learners is a strength. The RF (0.164) and LassoCV (0.165) estimates differ by less than 0.1 percentage points, and their confidence intervals overlap almost completely ([0.119, 0.208] vs [0.120, 0.209]). This near-identical performance is consistent with a setting where the nuisance functions are essentially constant (due to randomization), so learner choice should not matter.</p>
<p>The 23.9% magnitude difference between the DML and published IV estimates warrants more discussion. The paper notes this difference but attributes it only to “differences in how nuisance parameters are estimated.” Given that this is a randomized experiment with minimal confounding, the DML adjustment should be small in theory. The 24% shift is somewhat larger than expected and could reflect: (a) the DML model dropping 380 observations, (b) differences in how fixed effects are handled (the DML includes ddd_* dummies as covariates rather than absorbed FE), or (c) the cross-fitting procedure slightly changing the effective sample weights. The paper should investigate which of these factors drives the difference.</p>
<p>The diagnostics table in Section 4 is informative but the “FAIL” label for nuisance quality could mislead readers who do not read the accompanying text. The explanation in the text is thorough and correct, but the table should carry more of this nuance.</p>
</section>
</div>
<div id="tabset-1-7" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-7-tab">

</div>
<div id="tabset-1-8" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-8-tab">
<p><strong>Unified verdict:</strong> Minor revision</p>
<section id="blocking-issues-require-re-running-a-notebook" class="level3">
<h3 class="anchored" data-anchor-id="blocking-issues-require-re-running-a-notebook">Blocking issues (require re-running a notebook)</h3>
<p>None.</p>
</section>
<section id="major-issues-prose-or-table-edits-only" class="level3">
<h3 class="anchored" data-anchor-id="major-issues-prose-or-table-edits-only">Major issues (prose or table edits only)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>LATE estimand not explicitly restated in DML section – reader may confuse LATE with ATE, especially given GATE heterogeneity evidence</td>
<td>R1 (M1)</td>
<td>Add a sentence in Section 3.1 clarifying that the PLIV model targets the same LATE (complier-specific) estimand as the original 2SLS.</td>
</tr>
<tr class="even">
<td>2</td>
<td>Diagnostics table shows “FAIL” for nuisance quality without any in-table qualifier; misleading for table-only readers</td>
<td>R2 (M1), R3</td>
<td>Add a footnote or in-table note to the diagnostics table (Section 4) explaining that the nuisance FAIL is expected for randomized experiments.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>GATE CI labels say “joint” but are actually pointwise (separate subgroup fits)</td>
<td>R2 (m2)</td>
<td>Correct “joint CI” to “pointwise CI” in the GATE table caption (Table 3/tab:gate) and the gate_plot axis label. Paper text in Section 3.3 should also be corrected.</td>
</tr>
<tr class="even">
<td>4</td>
<td>Magnitude difference reported as “24.1%” in text but diagnostics JSON says 23.9%; inconsistent</td>
<td>R3 (M1)</td>
<td>Harmonize to “approximately 24%” or use the precise “23.9%” throughout.</td>
</tr>
</tbody>
</table>
</section>
<section id="minor-issues-3" class="level3">
<h3 class="anchored" data-anchor-id="minor-issues-3">Minor issues</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5</td>
<td>Sample size discrepancy (23,741 published vs 23,361 DML) not mentioned in text</td>
<td>R1 (m2), R3 (m3)</td>
<td>Add a sentence in Section 3.1 or 3.2 noting the 380-observation difference due to missing covariate values.</td>
</tr>
<tr class="even">
<td>6</td>
<td>GATE heterogeneity claim overstated – driven by tiny numhh=3 group; numhh=1 and numhh=2 CIs overlap</td>
<td>R1 (m3)</td>
<td>Soften language in Section 3.3 to “suggestive evidence” rather than “meaningful heterogeneity.”</td>
</tr>
<tr class="odd">
<td>7</td>
<td>First-stage F-statistic not reported for DML context</td>
<td>R1 (m1)</td>
<td>Add a note in Section 3.1 that the instrument remains strong in the DML framework.</td>
</tr>
<tr class="even">
<td>8</td>
<td>Only two learners used (RF, Lasso); no boosting method</td>
<td>R2 (m1)</td>
<td>Note in Section 3.1 that results are robust across the two learners tested; acknowledge boosting as a potential extension.</td>
</tr>
<tr class="odd">
<td>9</td>
<td>No causal forest analysis – should briefly explain why</td>
<td>R2 (m3)</td>
<td>Add a brief note explaining why causal forest was not used (PLIV design, categorical covariates).</td>
</tr>
<tr class="even">
<td>10</td>
<td>Preferred learner selection criterion is ad hoc (RF r2 &lt; 0.1 threshold)</td>
<td>R2 (m4)</td>
<td>Downplay “preferred” framing; emphasize robustness across both learners.</td>
</tr>
<tr class="odd">
<td>11</td>
<td>ITT and first-stage replication results not discussed in text, only in table</td>
<td>R3 (m1)</td>
<td>Add one sentence mentioning all three replicated specifications with their estimates.</td>
</tr>
<tr class="even">
<td>12</td>
<td>Missing robustness checks (alternative outcomes, without weights, subsample)</td>
<td>R3 (m4)</td>
<td>Add a limitations sentence in the conclusion acknowledging untested robustness dimensions.</td>
</tr>
<tr class="odd">
<td>13</td>
<td>DML-IV magnitude difference (24%) larger than expected for randomized experiment; possible drivers not discussed</td>
<td>R3</td>
<td>Add a sentence in Section 3.2 discussing possible drivers: sample difference, FE handling as covariates, cross-fitting.</td>
</tr>
</tbody>
</table>
</section>
<section id="referee-disagreements" class="level3">
<h3 class="anchored" data-anchor-id="referee-disagreements">Referee disagreements</h3>
<p>None. All three referees converge on a “Minor concerns” verdict. The issues are complementary, not contradictory.</p>
</section>
<section id="already-resolved-suppressed-from-this-round" class="level3">
<h3 class="anchored" data-anchor-id="already-resolved-suppressed-from-this-round">Already resolved (suppressed from this round)</h3>
<p>No prior rounds – nothing to suppress.</p>
</section>
</div>
<div id="tabset-1-9" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-9-tab">
<section id="final-review-report" class="level1">
<h1>Final Review Report</h1>
<p><strong>Paper:</strong> The Oregon Health Insurance Experiment: Evidence from the First Year <strong>Original authors:</strong> Finkelstein, A., Taubman, S., Wright, B., Bernstein, M., Gruber, J., Newhouse, J.P., Allen, H., Baicker, K. (<em>Quarterly Journal of Economics</em>, 2012) <strong>Rounds completed:</strong> 1 of 3 <strong>Final verdict:</strong> Ready</p>
<hr>
</section>
</div>
<div id="tabset-1-10" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-10-tab">
<p>This RECAST of Finkelstein et al.&nbsp;(2012) is a clean success. The replication is excellent – all three key specifications (IV/LATE, ITT, first stage) match the published estimates within 1.3% relative deviation. The DoubleML extension using the PLIV model is methodologically appropriate for the IV design and yields a point estimate (0.165) that is approximately 24% larger than the published IV (0.133) but fully compatible statistically: the published coefficient falls well within the DML 95% confidence interval [0.120, 0.209].</p>
<p>The DML extension contributes modest but real value over the original paper. It demonstrates that the IV results are robust to flexible, data-driven estimation of nuisance functions – a useful confirmation, though not surprising given the strength of the experimental design. The near-identical estimates across Random Forest (0.164) and LassoCV (0.165) further reinforce robustness. The GATE analysis by household size is a reasonable first pass at heterogeneity, finding suggestive evidence that two-person households benefit more from Medicaid than single-person households, though the confidence intervals overlap.</p>
<p>The paper would be publishable as a short replication-and-extension note in its current form. The main limitation is the narrow scope – only one outcome (self-reported health) is RECASTed, and only two ML learners are tested. The nuisance model FAIL is well-explained as a feature of the randomized design, not a bug.</p>
<hr>
</div>
<div id="tabset-1-11" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-11-tab">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 34%">
<col style="width: 38%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Raised (round)</th>
<th>Resolved (round)</th>
<th>How</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LATE estimand not restated in DML section</td>
<td>1</td>
<td>1</td>
<td>Added explicit sentence clarifying PLIV targets same LATE as 2SLS</td>
</tr>
<tr class="even">
<td>Diagnostics table FAIL misleading without qualifier</td>
<td>1</td>
<td>1</td>
<td>Added dagger footnote and explanatory text in the table</td>
</tr>
<tr class="odd">
<td>GATE CIs mislabeled as “joint” (actually pointwise)</td>
<td>1</td>
<td>1</td>
<td>Corrected labels in table and figure caption</td>
</tr>
<tr class="even">
<td>Magnitude difference inconsistent (24.1% vs 23.9%)</td>
<td>1</td>
<td>1</td>
<td>Harmonized to “approximately 24%”</td>
</tr>
<tr class="odd">
<td>Sample size discrepancy not documented</td>
<td>1</td>
<td>1</td>
<td>Added explanation of 380-observation difference (missing covariate values)</td>
</tr>
<tr class="even">
<td>Heterogeneity claim overstated</td>
<td>1</td>
<td>1</td>
<td>Softened to “suggestive evidence”; noted overlapping CIs</td>
</tr>
<tr class="odd">
<td>First-stage F not discussed for DML</td>
<td>1</td>
<td>1</td>
<td>Added note that instrument remains strong in DML context</td>
</tr>
<tr class="even">
<td>No explanation for absent causal forest</td>
<td>1</td>
<td>1</td>
<td>Added rationale (IV design + categorical covariate)</td>
</tr>
<tr class="odd">
<td>ITT and first-stage not discussed in text</td>
<td>1</td>
<td>1</td>
<td>Added specific estimates to replication section</td>
</tr>
<tr class="even">
<td>Missing limitations discussion</td>
<td>1</td>
<td>1</td>
<td>Added limitations paragraph to conclusion</td>
</tr>
<tr class="odd">
<td>DML-IV magnitude difference unexplained</td>
<td>1</td>
<td>1</td>
<td>Added discussion of possible drivers (sample diff, FE handling, cross-fitting)</td>
</tr>
<tr class="even">
<td>Learner selection criterion ad hoc</td>
<td>1</td>
<td>1</td>
<td>Reframed as robustness across learners rather than “preferred”</td>
</tr>
<tr class="odd">
<td>Only two learners tested</td>
<td>1</td>
<td>1</td>
<td>Acknowledged as limitation; suggested boosting as extension</td>
</tr>
</tbody>
</table>
<hr>
</div>
<div id="tabset-1-12" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-12-tab">
<table class="caption-top table">
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Severity</th>
<th>Action needed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>–</td>
<td>None</td>
<td>–</td>
<td>–</td>
</tr>
</tbody>
</table>
<p>All issues identified in Round 1 were resolved through paper.tex edits. No blocking issues requiring notebook re-runs were identified.</p>
<p><em>Severity: <strong>Blocking</strong> = must fix before sharing – <strong>Major</strong> = should fix – <strong>Minor</strong> = optional</em></p>
<hr>
</div>
<div id="tabset-1-13" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-13-tab">
<table class="caption-top table">
<colgroup>
<col style="width: 35%">
<col style="width: 25%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Specification</th>
<th>Estimate</th>
<th>SE</th>
<th>95% CI</th>
<th>N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Original paper (2SLS/IV)</td>
<td>0.133</td>
<td>0.026</td>
<td>[0.082, 0.184]</td>
<td>23,741</td>
</tr>
<tr class="even">
<td>Our replication (2SLS/IV)</td>
<td>0.132</td>
<td>0.026</td>
<td>[0.081, 0.184]</td>
<td>23,361</td>
</tr>
<tr class="odd">
<td>DML preferred (LassoCV)</td>
<td>0.165</td>
<td>0.023</td>
<td>[0.120, 0.209]</td>
<td>23,361</td>
</tr>
<tr class="even">
<td>DML alternative (RandomForest)</td>
<td>0.164</td>
<td>0.023</td>
<td>[0.119, 0.208]</td>
<td>23,361</td>
</tr>
</tbody>
</table>
<p><strong>Replication check:</strong> PASS – delta = 1.3% vs paper (worst across 3 specs)</p>
<p><strong>DML shift:</strong> The preferred DML estimate is 0.165 vs IV 0.133 – an upward shift of approximately 24% in magnitude. The published coefficient falls inside the DML 95% CI, so the estimates are statistically compatible. The DML standard error (0.023) is slightly smaller than the published SE (0.026), reflecting marginally more precise estimation.</p>
<hr>
</div>
<div id="tabset-1-14" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-14-tab">
<ul>
<li><p><strong>Nuisance R-squared is low by design.</strong> The outcome R-squared is 0.004 and the treatment R-squared is -0.28 (worse than predicting the mean). This is expected in a randomized lottery experiment where treatment assignment is independent of covariates. The DML Neyman-orthogonal score is robust to poor nuisance estimation, so this does not invalidate the results.</p></li>
<li><p><strong>GATE heterogeneity is suggestive, not conclusive.</strong> The numhh=1 (0.144) and numhh=2 (0.252) estimates have overlapping confidence intervals. The numhh=3 estimate (-1.336, N=57) is unreliable and should be ignored. No formal test of heterogeneity across groups is performed.</p></li>
<li><p><strong>Only one outcome is RECASTed.</strong> The original paper examines health care utilization, financial strain, and multiple health outcomes. Extending to additional outcomes would strengthen the analysis.</p></li>
<li><p><strong>The pipeline cannot verify data provenance or the original randomization.</strong> We take the lottery as random because the original authors demonstrate balance in the published paper. This RECAST relies on the same data and cannot independently verify data integrity.</p></li>
<li><p><strong>Survey weights are used in the replication but not in DML.</strong> The DoubleML framework does not natively support survey weights. The DML estimates are unweighted, which could contribute to the 24% magnitude difference. Testing sensitivity to weighting is a natural robustness check that would require manual implementation.</p></li>
</ul>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/qgallea\.github\.io\/recast-causal-ai");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>RECAST</strong> by <a href="https://thecausalmindset.com">Quentin Gallea, Ph.D.</a> · Built with <a href="https://claude.ai/code">Claude Code</a> &amp; <a href="https://quarto.org">Quarto</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/qgallea/recast-causal-ai">GitHub</a> · <a href="https://thecausalmindset.com/training/claude-code-for-research">Claude Code for Research</a></p>
</div>
  </div>
</footer>




</body></html>