<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Djankov, Ganser, McLiesh, Ramalho &amp; Shleifer">
<meta name="dcterms.date" content="2010-01-01">
<meta name="description" content="Cross-country OLS: do higher corporate tax rates reduce investment and entrepreneurship?">

<title>The Effect of Corporate Taxes on Investment and Entrepreneurship – RECAST</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6cd8083c2b52a75285f27e87131d3d27.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var banner = document.createElement('div');
  banner.className = 'construction-banner';
  banner.innerHTML = '&#x1F6A7; <strong>Under construction &amp; testing</strong> &mdash; This site is in active development. Results have not been independently verified. Do not cite or rely on any output without manual review.';
  document.body.insertBefore(banner, document.body.firstChild);
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">RECAST</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../papers.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../framework.html"> 
<span class="menu-text">Framework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../submissions.html"> 
<span class="menu-text">Tracker</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../submit.html"> 
<span class="menu-text">Submit</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/qgallea/recast-causal-ai"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#paper-summary" id="toc-paper-summary" class="nav-link active" data-scroll-target="#paper-summary">Paper summary</a></li>
  <li><a href="#replication-results" id="toc-replication-results" class="nav-link" data-scroll-target="#replication-results">Replication results</a></li>
  <li><a href="#dml-extension" id="toc-dml-extension" class="nav-link" data-scroll-target="#dml-extension">DML Extension</a></li>
  <li><a href="#what-did-causal-ml-add-here" id="toc-what-did-causal-ml-add-here" class="nav-link" data-scroll-target="#what-did-causal-ml-add-here">What did causal ML add here?</a></li>
  <li><a href="#referee-reports" id="toc-referee-reports" class="nav-link" data-scroll-target="#referee-reports">Referee reports</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Effect of Corporate Taxes on Investment and Entrepreneurship</h1>
  <div class="quarto-categories">
    <div class="quarto-category">OLS</div>
    <div class="quarto-category">Public Finance</div>
    <div class="quarto-category">Taxation</div>
    <div class="quarto-category">2010</div>
    <div class="quarto-category">PASS</div>
  </div>
  </div>

<div>
  <div class="description">
    Cross-country OLS: do higher corporate tax rates reduce investment and entrepreneurship?
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Djankov, Ganser, McLiesh, Ramalho &amp; Shleifer </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2010</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="paper-summary" class="level2">
<h2 class="anchored" data-anchor-id="paper-summary">Paper summary</h2>
<p><strong>Citation:</strong> Djankov, S., Ganser, T., McLiesh, C., Ramalho, R. &amp; Shleifer, A. (2010). “The Effect of Corporate Taxes on Investment and Entrepreneurship.” <em>American Economic Journal: Macroeconomics</em>, 2(3), 31–64. <a href="https://doi.org/10.1257/mac.2.3.31">DOI</a></p>
<p><strong>Identification strategy:</strong> Cross-country OLS regressions estimating the effect of corporate tax rates on investment and entrepreneurship for the year 2004. Three measures of corporate taxes (statutory rate, first-year effective rate, five-year effective rate) and four outcome variables (investment/GDP, FDI/GDP, business density, entry rate), with 12 control variables from the Baiardi &amp; Naghi (2024) replication code.</p>
<p><strong>Key original result:</strong> Higher corporate taxes are associated with lower investment and entrepreneurship. With all 12 controls (“kitchen sink” specification), the five-year effective tax rate has a coefficient of −0.189 (SE 0.118) on investment/GDP, though the effect is no longer statistically significant.</p>
<p><strong>Reference:</strong> This paper was revisited by <a href="https://doi.org/10.1093/ectj/utae004">Baiardi &amp; Naghi (2024, <em>Econometrics Journal</em>)</a>, who applied DML with 7 ML methods and found larger, often significant negative effects.</p>
<hr>
</section>
<section id="replication-results" class="level2">
<h2 class="anchored" data-anchor-id="replication-results">Replication results</h2>
<p>The replication is <strong>successful</strong>. All 12 OLS coefficients (4 outcomes × 3 tax measures) match the Baiardi &amp; Naghi (2024) reference within 0.69% maximum deviation. Sample sizes match exactly.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Specification (effective_5yr)</th>
<th>Published</th>
<th>Replicated</th>
<th>Δ (%)</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Panel A: Investment/GDP</td>
<td>−0.189</td>
<td>−0.189</td>
<td>0.13%</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>Panel B: FDI/GDP</td>
<td>−0.095</td>
<td>−0.095</td>
<td>0.35%</td>
<td>PASS</td>
</tr>
<tr class="odd">
<td>Panel C: Business density</td>
<td>−0.070</td>
<td>−0.070</td>
<td>0.69%</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>Panel D: Entry rate</td>
<td>−0.133</td>
<td>−0.133</td>
<td>0.23%</td>
<td>PASS</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forest_plot.png" class="img-fluid figure-img"></p>
<figcaption>Forest plot: OLS vs.&nbsp;DML estimates across methods</figcaption>
</figure>
</div>
<hr>
</section>
<section id="dml-extension" class="level2">
<h2 class="anchored" data-anchor-id="dml-extension">DML Extension</h2>
<p>Double/Debiased Machine Learning was applied using the <strong>PLR</strong> (Partially Linear Regression) model with adaptive cross-fitting (K=2), 6 ML methods + Ensemble + Best, and 5 repetitions with median aggregation. All 12 specifications (4 outcomes × 3 tax measures) were estimated.</p>
<section id="key-results-five-year-effective-tax-rate" class="level3">
<h3 class="anchored" data-anchor-id="key-results-five-year-effective-tax-rate">Key results (five-year effective tax rate)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>Panel</th>
<th>OLS</th>
<th>Lasso</th>
<th>Boosting</th>
<th>Forest</th>
<th>Best</th>
<th>N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A: Investment</td>
<td>−0.189</td>
<td>−0.238</td>
<td>−0.234</td>
<td>−0.211**</td>
<td>−0.211**</td>
<td>61</td>
</tr>
<tr class="even">
<td>B: FDI</td>
<td>−0.095</td>
<td>−0.148</td>
<td>−0.167*</td>
<td>−0.187**</td>
<td>−0.187**</td>
<td>61</td>
</tr>
<tr class="odd">
<td>C: Business density</td>
<td>−0.070</td>
<td>−0.139*</td>
<td>−0.108</td>
<td>−0.122*</td>
<td>−0.122*</td>
<td>60</td>
</tr>
<tr class="even">
<td>D: Entry rate</td>
<td>−0.133</td>
<td>−0.160*</td>
<td>−0.194**</td>
<td>−0.173**</td>
<td>−0.173**</td>
<td>50</td>
</tr>
</tbody>
</table>
<p><em>Stars: * p&lt;0.10, ** p&lt;0.05, *** p&lt;0.01. Best = Random Forest (lowest nuisance MSE).</em></p>
<p><strong>Key finding:</strong> DML recovers significant negative tax effects across <strong>all 4 outcomes</strong>, where OLS with all controls was insignificant. The DML Forest estimate for Investment (−0.211, p=0.008) closely matches the independent Baiardi &amp; Naghi benchmark (−0.204). Five of six learners agree on the negative sign; only NeuralNet (+0.063) diverges, consistent with small-sample noise.</p>
</section>
<section id="heterogeneous-treatment-effects" class="level3">
<h3 class="anchored" data-anchor-id="heterogeneous-treatment-effects">Heterogeneous treatment effects</h3>
<p><strong>BLP test:</strong> β₂ = 1.039 (p &lt; 0.001) — significant heterogeneity detected.</p>
<p><strong>GATE analysis</strong> (5 quintiles of predicted CATE) shows a clear gradient: countries most negatively affected by corporate taxes (Q1: −1.72) differ substantially from least affected (Q5: +1.34).</p>
<p><strong>CLAN analysis:</strong> Countries most affected by taxes tend to have higher trade freedom and lower inflation than least-affected countries.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="gate_plot.png" class="img-fluid figure-img"></p>
<figcaption>GATE estimates by quintile</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="what-did-causal-ml-add-here" class="level2">
<h2 class="anchored" data-anchor-id="what-did-causal-ml-add-here">What did causal ML add here?</h2>
<p>The DML extension adds genuine value. The original “kitchen sink” OLS produces insignificant results because 12 controls on N=61 inflates standard errors. DML’s data-driven variable selection and flexible nonlinear control keep a smaller set of influential confounders, producing <strong>larger absolute coefficients and lower standard errors</strong> — exactly the mechanism Baiardi &amp; Naghi (2024) identify.</p>
<p>The DML Forest estimate (−0.211) is within 3.4% of the independent B&amp;N benchmark (−0.204), providing strong external validation.</p>
<p>The BLP and GATE analyses reveal significant heterogeneity: the negative tax effect varies substantially across countries, with the strongest effects in countries with higher trade openness. This heterogeneity was not explored in the original paper.</p>
<hr>
</section>
<section id="referee-reports" class="level2">
<h2 class="anchored" data-anchor-id="referee-reports">Referee reports</h2>
<p><strong>Referee consensus:</strong> All three referees gave “Minor revision.” One essential issue (CLAN label inversion) was identified and fixed. Three optional suggestions were deferred. <strong>Final verdict: Ready.</strong></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Identification</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Referee 1 Report: Identification</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">DML Methods</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Referee 2 Report: DML Methods &amp; Causal Forest</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href="">Robustness</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false" href="">Referee 3 Report: Robustness and Replication</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-7-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-7" role="tab" aria-controls="tabset-1-7" aria-selected="false" href="">Synthesis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-8-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-8" role="tab" aria-controls="tabset-1-8" aria-selected="false" href="">Synthesis Report — Round 1</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-9-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-9" role="tab" aria-controls="tabset-1-9" aria-selected="false" href="">Final Report</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-10-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-10" role="tab" aria-controls="tabset-1-10" aria-selected="false" href="">What This RECAST Contributes</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-11-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-11" role="tab" aria-controls="tabset-1-11" aria-selected="false" href="">Replication Summary</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-12-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-12" role="tab" aria-controls="tabset-1-12" aria-selected="false" href="">DML Extension Summary</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-13-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-13" role="tab" aria-controls="tabset-1-13" aria-selected="false" href="">Review Process Summary</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-14-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-14" role="tab" aria-controls="tabset-1-14" aria-selected="false" href="">Remaining Items</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-15-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-15" role="tab" aria-controls="tabset-1-15" aria-selected="false" href="">Notes for the Reader</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">

</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor revision</p>
<section id="contribution-assessment" class="level3">
<h3 class="anchored" data-anchor-id="contribution-assessment">Contribution assessment</h3>
<p>This RECAST adds genuine value. The original Djankov et al.&nbsp;(2010) paper estimates the effect of corporate taxes on investment using OLS with 12 controls in a sample of roughly 60 countries — a setting where p/N is large enough that OLS suffers from efficiency loss and overfitting bias. The DML extension relaxes the linear functional form assumption on the nuisance functions, allows data-driven variable selection across the 12-dimensional control set, and produces a debiased treatment effect estimate via cross-fitting. The result — a Forest coefficient of -0.211 (p = 0.008) that closely matches the independent Baiardi &amp; Naghi (2024) benchmark of -0.204 — demonstrates that the original finding survives a substantially more flexible estimation approach and, indeed, gains statistical significance that OLS could not deliver.</p>
</section>
<section id="essential-issues-must-be-addressed-paper-is-unpublishable-without-these" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues-must-be-addressed-paper-is-unpublishable-without-these">Essential issues (must be addressed — paper is unpublishable without these)</h3>
<p>None — identification is sound.</p>
<p>The paper correctly identifies that the original study relies on selection-on-observables (OLS with controls) rather than an IV or quasi-experimental design. The DML PLR model preserves this identification assumption: it estimates the same linear treatment effect parameter theta under the same conditional independence condition, differing only in how the nuisance functions g(X) and m(X) are estimated. The estimand (the partial effect of the tax rate on the outcome, conditional on controls) is clearly defined and consistently targeted across OLS and DML. No identification logic is altered by the extension.</p>
</section>
<section id="suggestions-would-improve-the-paper-but-optional" class="level3">
<h3 class="anchored" data-anchor-id="suggestions-would-improve-the-paper-but-optional">Suggestions (would improve the paper, but optional)</h3>
<ol type="1">
<li><p><strong>Acknowledge the selection-on-observables limitation explicitly in the conclusion.</strong> The paper does a good job describing the original identification strategy in Section 2, but the conclusion (Section 5) could benefit from a single sentence noting that neither OLS nor DML resolves potential endogeneity from omitted confounders (e.g., political institutions that jointly determine tax policy and investment climate). The DML extension strengthens efficiency and relaxes functional form, but it does not substitute for exogenous variation. This is well understood by the target audience, but stating it prevents over-interpretation.</p></li>
<li><p><strong>Briefly discuss the nuisance model R-squared in the identification context.</strong> The diagnostics table (Table 5) reports average nuisance R-squared values of -0.43 (outcome) and -0.18 (treatment). The paper correctly notes this reflects small-sample ML overfitting and that the best learner (Forest) achieves positive R-squared. From an identification standpoint, low R-squared in the treatment model m(X) means the controls explain little of the variation in tax rates — which actually supports the plausibility of the partially linear model, since it implies the treatment has substantial residual variation not collinear with X. This could be mentioned as a minor point in the diagnostics discussion to reassure readers.</p></li>
<li><p><strong>Consider noting that the GATE gradient (Q1: -1.72 to Q5: +1.34) is descriptive, not causal at the subgroup level.</strong> The BLP test and GATE analysis in Section 3.2 are informative, and the CLAN finding about trade freedom is suggestive. However, the GATE estimates are conditional on predicted CATEs from a first-stage model, and in N = 61 with 12 quintile bins of approximately 12 observations each, the extreme quintile estimates are necessarily imprecise (as the wide CIs confirm). The paper could add a sentence noting that the heterogeneity results should be interpreted as exploratory evidence of effect variation rather than as well-identified subgroup causal effects.</p></li>
</ol>
</section>
<section id="comments-to-the-authors" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors">Comments to the authors</h3>
<p>This is a well-executed RECAST. The replication is essentially exact (0.69% worst deviation, all sample sizes matching), and the DML extension provides a meaningful robustness check that strengthens the original paper’s conclusions. The close alignment with the independent Baiardi &amp; Naghi (2024) Forest estimate (-0.211 vs.&nbsp;-0.204) is reassuring and suggests the pipeline is correctly implemented. The choice of PLR as the DML model is appropriate given that the original design uses OLS with a continuous treatment and no instruments.</p>
<p>The sign agreement across learners (5/6 negative) and the cross-fit stability (ratio = 0.21) both support the credibility of the main DML result. The neural network divergence is appropriately flagged and convincingly attributed to small-sample variance. The heterogeneous treatment effect analysis is a genuine contribution beyond what the original paper or Baiardi &amp; Naghi (2024) provide, and the finding that trade openness moderates the tax-investment relationship is economically intuitive. Overall, the identification strategy is preserved and well-documented, and the paper should proceed with at most minor revisions.</p>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">

</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor revision</p>
<hr>
<section id="methodological-contribution" class="level3">
<h3 class="anchored" data-anchor-id="methodological-contribution">Methodological contribution</h3>
<p>The DML extension is well-suited to Djankov et al.&nbsp;(2010). The original setting – cross-country OLS with a continuous treatment (corporate tax rates) and 12 controls in a sample of N=50–61 – is exactly the regime where DML offers value: p/N is large (~0.2), OLS with many controls is inefficient, and the PLR model cleanly nests the original specification. Comparing six ML learners across all 12 specifications provides genuine evidence about the robustness of the original result and aligns well with the Baiardi &amp; Naghi (2024) benchmark. The systematic finding that DML recovers larger and more significant negative coefficients than OLS, particularly for Investment and FDI, is the central value added.</p>
<hr>
</section>
<section id="dml-checklist" class="level3">
<h3 class="anchored" data-anchor-id="dml-checklist">DML checklist</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 24%">
<col style="width: 36%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Item</th>
<th>Verdict</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Model class (PLR) correct</td>
<td><strong>PASS</strong></td>
<td>PLR is correct for continuous treatment with no instruments.</td>
</tr>
<tr class="even">
<td>2</td>
<td>K-fold adaptive to N</td>
<td><strong>PASS</strong></td>
<td>K=2 for N&lt;200. All specifications use N=50–61, so K=2 is appropriate.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>n_rep &gt;= 20, median aggregation, adjusted SE</td>
<td><strong>SUGGESTION</strong> (S1)</td>
<td>n_rep=5 with median aggregation and B&amp;N adjusted SE formula. See S1 below.</td>
</tr>
<tr class="even">
<td>4</td>
<td>“Best” selected by lowest nuisance MSE</td>
<td><strong>PASS</strong></td>
<td>Code confirms: <code>best_method = min(methods_ok, key=lambda m: learner_nuisance_mse[m]['mse_outcome'])</code>. Selection is by outcome nuisance MSE, not p-value.</td>
</tr>
<tr class="odd">
<td>5</td>
<td>&gt;= 5 method classes present</td>
<td><strong>PASS</strong></td>
<td>6 learners (Lasso, ElasticNet, DecisionTree, Boosting, Forest, NeuralNet) + Ensemble + Best = 8 columns.</td>
</tr>
<tr class="even">
<td>6</td>
<td>Nuisance R^2 reported and honestly interpreted</td>
<td><strong>PASS</strong></td>
<td>Paper Table 4 discusses negative average R^2 and reports Forest best R^2_Y=0.051, R^2_D=0.090. Diagnostics section acknowledges this is a small-sample limitation.</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Score function appropriate</td>
<td><strong>PASS</strong></td>
<td>Default DoubleML PLR score (partialling out) is used, which is correct.</td>
</tr>
<tr class="even">
<td>8</td>
<td>CIs from DML SEs (not naive OLS post-residualisation)</td>
<td><strong>PASS</strong></td>
<td>CIs are computed as <code>median_coef +/- 1.96 * SE_adj</code> using the B&amp;N adjusted formula.</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Lasso coefficient diagnostics reported</td>
<td><strong>SUGGESTION</strong> (S2)</td>
<td><code>lasso_diagnostics: null</code> for all specifications in the JSON. The <code>extract_lasso_diagnostics</code> function exists in the code but appears to have failed silently (likely a key-format issue across DoubleML versions).</td>
</tr>
<tr class="even">
<td>10</td>
<td>BLP heterogeneity test reported before GATE</td>
<td><strong>PASS</strong></td>
<td>BLP beta_2 = 1.039, p &lt; 0.001. Correctly reported before GATE analysis.</td>
</tr>
<tr class="odd">
<td>11</td>
<td>GATE groups based on predicted CATE quintiles</td>
<td><strong>PASS</strong></td>
<td>Code uses <code>pd.qcut(S_proxy, q=5)</code> on predicted CATE from the Best learner.</td>
</tr>
<tr class="even">
<td>12</td>
<td>Jointly valid CIs for GATE</td>
<td><strong>PASS</strong></td>
<td>Code confirms <code>gate_obj.confint(level=0.95, joint=True)</code>.</td>
</tr>
<tr class="odd">
<td>13</td>
<td>CLAN included</td>
<td><strong>PASS</strong></td>
<td>CLAN is reported in the paper (Table 5) and JSON (12 control variables compared). See E1 below for a labeling concern.</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="essential-issues" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues">Essential issues</h3>
<p><strong>E1. CLAN labeling inversion: “most affected” and “least affected” groups appear swapped.</strong></p>
<p>The CLAN code defines <code>top_q = S_proxy &gt;= np.percentile(S_proxy, 80)</code> – that is, the top quintile of the predicted CATE distribution. Since the overall treatment effect is negative (taxes reduce investment), a <em>high</em> predicted CATE means the country is <em>least</em> negatively affected (near-zero or positive CATE), while a <em>low</em> predicted CATE means the country is <em>most</em> negatively affected. However, the code labels the top-CATE group as “Most” (mapped to <code>mean_most_affected</code> in the JSON) and the bottom-CATE group as “Least” (mapped to <code>mean_least_affected</code>).</p>
<p>This means the paper’s CLAN discussion has the group labels inverted: when it states “the most affected countries have lower trade freedom (mean 6.72) than the least affected (mean 7.52),” it is actually describing the <em>least</em> harmed countries (Q5, positive CATE) as “most affected” and the <em>most</em> harmed countries (Q1, negative CATE) as “least affected.”</p>
<p><strong>Scientific justification:</strong> This does not change any computed values (the t-test and means are correct), but it inverts the substantive interpretation of which country characteristics predict larger or smaller treatment effects. The CLAN paragraph in the paper draws a causal-intuition narrative (“countries with less open economies suffer more from corporate tax increases”) that is backwards relative to the actual GATE gradient. Without correction, readers will draw the wrong policy conclusion from the CLAN table.</p>
<p><strong>Fix:</strong> Swap the labels so that <code>bot_q</code> (lowest predicted CATE = most negative effect = most harmed) is “most affected” and <code>top_q</code> (highest predicted CATE = least negative effect) is “least affected.” Update the CLAN discussion in the paper accordingly.</p>
<hr>
</section>
<section id="suggestions" class="level3">
<h3 class="anchored" data-anchor-id="suggestions">Suggestions</h3>
<p><strong>S1. Consider increasing n_rep from 5 to at least 20.</strong></p>
<p>The current n_rep=5 is below the standard recommendation of n_rep &gt;= 20 (Chernozhukov et al., 2018). The B&amp;N adjusted SE formula is designed to account for cross-split variation, but with only 5 repetitions the median estimate may have non-trivial sampling noise. The cross-fit stability diagnostic (SD across reps = 0.016, ratio = 0.21 for Forest) is reassuring for the primary specification, so this is not blocking. However, increasing to n_rep=20 would better justify the asymptotic validity of the adjusted SE. This is a suggestion because the current results are stable and match the B&amp;N benchmark, so there is no evidence of bias from low n_rep.</p>
<p><strong>S2. Report Lasso variable selection diagnostics.</strong></p>
<p>The <code>lasso_diagnostics</code> field is <code>null</code> for every specification, meaning Lasso/ElasticNet coefficient counts and top selected variables are not reported. The <code>extract_lasso_diagnostics</code> function exists but apparently fails due to a key-format mismatch across DoubleML versions. Reporting which controls Lasso retains (and which it zeros out) would help readers understand why DML recovers larger coefficients than OLS – the standard interpretation is that OLS is inefficient because it tries to estimate all 12 control coefficients, while Lasso shrinks irrelevant ones. This is informative but not essential.</p>
<p><strong>S3. Discuss the “Best” learner selection criterion more transparently.</strong></p>
<p>The “Best” learner is selected by lowest <em>outcome</em> nuisance MSE (<code>mse_outcome</code>), but the best method for the treatment nuisance can differ. For the primary specification (Investment ~ 5yr effective rate), Best selects Forest (R^2_Y = 0.051) for the outcome equation but the JSON records <code>best_treatment_method: ElasticNet</code>. The paper and diagnostics table do not explain this asymmetry. A brief note clarifying that “Best” refers to the learner with the lowest outcome MSE (and why this is the standard choice) would improve transparency.</p>
<p><strong>S4. Note the DecisionTree anomaly in some specifications.</strong></p>
<p>In Panel C (Business density ~ statutory), the Best learner is DecisionTree with R^2_Y = 0.115 and coefficient -0.037 (p = 0.70). In the same panel, Forest yields -0.089 (p = 0.11) and Lasso yields -0.115 (p = 0.04). DecisionTree is selected as “Best” on MSE grounds, but its coefficient is the smallest and least significant. This is not wrong – MSE-based selection is methodologically correct – but it highlights that “Best” does not always mean “most significant” or “most informative.” A sentence acknowledging this would prevent misunderstanding.</p>
<hr>
</section>
<section id="comments-to-the-authors-1" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors-1">Comments to the authors</h3>
<p>The DML implementation is methodologically sound. The use of PLR, K=2 folds for N &lt; 200, median aggregation with B&amp;N adjusted SEs, and “Best” selection by nuisance MSE all follow the Baiardi &amp; Naghi (2024) protocol. The close match between the pipeline’s Forest estimate (-0.211, SE=0.079) and the B&amp;N benchmark (-0.204, SE=0.094) for the primary specification is striking and lends credibility to the entire analysis. The finding that 5/6 learners agree on a negative sign, with only the neural network diverging (as expected in N=61), is exactly the kind of robustness evidence that DML is designed to provide. The nuisance model quality issue (average R^2 &lt; 0) is an inherent limitation of ML in small cross-country samples and is honestly discussed; the Forest’s positive R^2 (0.051 for outcome, 0.090 for treatment) is modest but sufficient for valid DML inference, as confirmed by the low cross-fit ratio (0.21).</p>
<p>The heterogeneous treatment effect analysis is well-executed. The BLP test correctly rejects constant effects (beta_2 = 1.04, p &lt; 0.001), and the GATE gradient from -1.72 (Q1) to +1.34 (Q5) with jointly valid CIs is a valuable finding that goes beyond the original paper. The one essential issue (E1) concerns the CLAN labeling, which should be corrected to avoid misleading substantive interpretation. The re-fitting with n_rep=1 for GATE compatibility is a reasonable workaround for the DoubleML API constraint.</p>
</section>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">

</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor revision</p>
<section id="replication-assessment" class="level3">
<h3 class="anchored" data-anchor-id="replication-assessment">Replication assessment</h3>
<p>The replication is a clear success. All four reference specifications (Investment, FDI, Business density, Entry rate regressed on the five-year effective tax rate with 12 controls) replicate within a 0.69% maximum deviation, with exact sample-size matches (<span class="math inline">\(N = 61, 61, 60, 50\)</span>). All signs are correct. The 4/4 pass rate against the Baiardi &amp; Naghi (2024) benchmarks leaves no doubt about the fidelity of the data processing and regression implementation.</p>
</section>
<section id="essential-issues-1" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues-1">Essential issues</h3>
<p>None — replication is adequate and the core DML results are well-supported.</p>
</section>
<section id="suggestions-1" class="level3">
<h3 class="anchored" data-anchor-id="suggestions-1">Suggestions</h3>
<ol type="1">
<li><p><strong>Lasso p-value rounding in FDI panel (Panel B).</strong> The paper reports the FDI Lasso estimate as “<span class="math inline">\(-0.148\)</span>, <span class="math inline">\(p = 0.05\)</span>”. The JSON records <span class="math inline">\(p = 0.053\)</span>, which strictly rounds to <span class="math inline">\(0.05\)</span> only at one decimal place. Since the narrative frames Lasso as “significant at 5%,” the authors should either report the p-value to two decimal places (<span class="math inline">\(p = 0.05\)</span>, which is defensible) or explicitly note “marginally significant” to avoid any impression of cherry-picked rounding. This is cosmetic but worth fixing in one pass.</p></li>
<li><p><strong>Nuisance <span class="math inline">\(R^2\)</span> discussion could be tightened.</strong> The diagnostics table correctly reports the FAIL flag (average <span class="math inline">\(R^2_Y = -0.43\)</span>, <span class="math inline">\(R^2_D = -0.18\)</span>) and the discussion paragraph provides a clear explanation: small-sample ML overfitting drives negative averages, while the best learner (Forest) achieves positive <span class="math inline">\(R^2\)</span>. This is transparent and adequate. A small improvement would be to note explicitly that the B&amp;N adjusted SE formula already penalises unstable nuisance estimates, so the FAIL flag does not mechanically invalidate the confidence intervals. One sentence would suffice.</p></li>
<li><p><strong>Neural network sign disagreement across panels.</strong> The paper correctly highlights that NeuralNet diverges in the primary specification (Investment panel: <span class="math inline">\(+0.063\)</span>, <span class="math inline">\(p = 0.61\)</span>) and attributes this to small-sample instability. It is worth noting for completeness that the NeuralNet <em>agrees</em> on a negative sign in the other three panels (FDI: <span class="math inline">\(-0.113\)</span>; Business density: <span class="math inline">\(-0.048\)</span>; Entry rate: <span class="math inline">\(-0.191\)</span>, <span class="math inline">\(p &lt; 0.01\)</span>). This strengthens the argument that the Investment-panel disagreement is noise rather than a systematic concern. A brief parenthetical would suffice.</p></li>
<li><p><strong>Forest plot inspection.</strong> The forest plot displays all four panels (A–D) with OLS, six individual learners, Ensemble, and Best for the five-year effective rate. Visual inspection confirms: (a) all DML point estimates in Panels A, B, and D are left of OLS, consistent with the narrative that DML recovers larger effects; (b) confidence intervals for tree-based methods exclude zero in Panel A, matching the reported significance; (c) the NeuralNet estimate in Panel A is the only point clearly to the right of zero; (d) Panel D shows the tightest clustering of learners, consistent with the claim that all six are significant. The plot is accurate and well-constructed. One minor visual note: the Ensemble and Best markers use a different colour (green) which aids readability, but no legend explains the colour coding — adding a legend entry would improve standalone interpretability.</p></li>
</ol>
</section>
<section id="comments-to-the-authors-2" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors-2">Comments to the authors</h3>
<p>The replication component of this paper is exemplary. A 0.69% worst-case deviation across four specifications, with exact sample-size matches and correct signs throughout, sets a high standard for automated replication. The choice to benchmark against Baiardi &amp; Naghi (2024) Table 1 provides a credible external reference, and the match between the pipeline’s Forest estimate (<span class="math inline">\(-0.211\)</span>) and the published Forest benchmark (<span class="math inline">\(-0.204\)</span>) — an 18.5% relative difference with CI overlap — further validates the DML implementation.</p>
<p>The robustness picture is strong. Across the 12 outcome-treatment combinations, the DML estimates consistently recover larger negative coefficients than OLS, with several achieving significance where OLS does not. The cross-fit stability ratio of 0.21 (Forest, primary spec) indicates that the variation across repetitions is modest relative to sampling uncertainty, which is reassuring. The learner sign agreement (5/6 negative in the primary spec, 6/6 negative in the entry rate panel) provides a natural robustness check that the results do not depend on a single ML method. The sole diagnostic concern — negative average nuisance <span class="math inline">\(R^2\)</span> — is a known consequence of applying cross-validated ML to <span class="math inline">\(N \approx 60\)</span> with 12 controls, and the paper handles this transparently. The suggestions above are cosmetic improvements that would strengthen an already well-executed analysis; none rises to the level of an essential revision.</p>
</section>
</div>
<div id="tabset-1-7" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-7-tab">

</div>
<div id="tabset-1-8" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-8-tab">
<p><strong>Unified verdict:</strong> Minor revision</p>
<section id="contribution-consensus" class="level3">
<h3 class="anchored" data-anchor-id="contribution-consensus">Contribution consensus</h3>
<p>All three referees agree that this RECAST adds genuine value. The original Djankov et al.&nbsp;(2010) setting – cross-country OLS with a continuous treatment, 12 controls, and N approximately 60 – is exactly the regime where DML offers efficiency gains. The close match between the pipeline’s Forest estimate (-0.211) and the independent Baiardi &amp; Naghi (2024) benchmark (-0.204) validates the implementation. The heterogeneous treatment effect analysis (BLP test, GATE, CLAN) extends the original paper in a direction neither Djankov et al.&nbsp;nor Baiardi &amp; Naghi pursued, providing novel evidence that the tax-investment relationship varies systematically across countries. The contribution bar is met; the bar for blocking is correspondingly higher.</p>
</section>
<section id="essential-issues-must-be-addressed-paper-cannot-stand-as-is" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues-must-be-addressed-paper-cannot-stand-as-is">Essential issues (must be addressed — paper cannot stand as-is)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 46%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Scientific justification</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E1</td>
<td>CLAN labeling inversion: the code maps <code>top_q</code> (highest predicted CATE = least negatively affected) to “most affected” and <code>bot_q</code> (lowest predicted CATE = most negatively affected) to “least affected,” inverting the group labels in the JSON output.</td>
<td>R2</td>
<td>The paper’s CLAN narrative draws a substantive conclusion (“countries with less open economies suffer more from corporate tax increases”) that may be backwards relative to the actual GATE gradient if the means are assigned to the wrong groups. Without correction, readers draw the wrong policy implication from the CLAN table. The paper text correctly defines Q1 as “most affected” and Q5 as “least affected” (line 229), but the underlying data feeding those means may be swapped in the code.</td>
<td>Fix the CLAN label assignment in <code>code_build/04_dml_extension.ipynb</code> so that <code>bot_q</code> (lowest CATE = most harmed) maps to “most affected” and <code>top_q</code> (highest CATE = least harmed) maps to “least affected.” Re-run the notebook and verify that the CLAN means in the JSON match the corrected labels. Update the paper text only if the reported means change.</td>
</tr>
</tbody>
</table>
</section>
<section id="suggestions-would-improve-but-are-optional" class="level3">
<h3 class="anchored" data-anchor-id="suggestions-would-improve-but-are-optional">Suggestions (would improve but are optional)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S1</td>
<td>Acknowledge the selection-on-observables limitation in the conclusion. Neither OLS nor DML resolves potential endogeneity from omitted confounders.</td>
<td>R1</td>
<td>Add one sentence to the conclusion noting that the DML extension strengthens efficiency and relaxes functional form but does not substitute for exogenous variation.</td>
</tr>
<tr class="even">
<td>S2</td>
<td>Tighten the nuisance R-squared discussion. (a) In the identification context, note that low R-squared in the treatment model m(X) implies substantial residual treatment variation, which supports the PLR model. (b) Note that the B&amp;N adjusted SE formula already penalises unstable nuisance estimates, so the FAIL flag does not mechanically invalidate the CIs.</td>
<td>R1, R3</td>
<td>Add one to two sentences to the diagnostics discussion combining both points.</td>
</tr>
<tr class="odd">
<td>S3</td>
<td>Note that the GATE gradient is descriptive, not causal at the subgroup level. With N = 61 split into quintiles of ~12 observations, extreme-quintile estimates are imprecise.</td>
<td>R1</td>
<td>Add a sentence to the GATE discussion noting the exploratory nature of the heterogeneity results.</td>
</tr>
<tr class="even">
<td>S4</td>
<td>Consider increasing n_rep from 5 to at least 20 for better asymptotic justification of the adjusted SE.</td>
<td>R2</td>
<td>Optional. Current results are stable (cross-fit ratio = 0.21) and match the benchmark, so there is no evidence of bias. If computationally feasible, increase; otherwise, add a sentence justifying n_rep = 5 given the small sample.</td>
</tr>
<tr class="odd">
<td>S5</td>
<td>Report Lasso variable selection diagnostics. The <code>lasso_diagnostics</code> field is null due to a likely key-format issue.</td>
<td>R2</td>
<td>Fix the <code>extract_lasso_diagnostics</code> function if possible. If not feasible, add a footnote noting the limitation.</td>
</tr>
<tr class="even">
<td>S6</td>
<td>Clarify the “Best” learner selection criterion. Best is selected by lowest outcome nuisance MSE, but the best treatment-model learner can differ.</td>
<td>R2</td>
<td>Add a brief note in the methods section explaining that “Best” refers to the learner with the lowest outcome MSE and why this is the standard choice.</td>
</tr>
<tr class="odd">
<td>S7</td>
<td>Note the DecisionTree anomaly in Panel C: Best selects DecisionTree on MSE grounds, but its coefficient is smallest and least significant.</td>
<td>R2</td>
<td>Add one sentence acknowledging that MSE-based selection does not always select the most significant learner.</td>
</tr>
<tr class="even">
<td>S8</td>
<td>Report FDI Lasso p-value more precisely. JSON records p = 0.053; paper says p = 0.05.</td>
<td>R3</td>
<td>Either report to two decimal places (p = 0.05) with a note, or say “marginally significant (p = 0.053).”</td>
</tr>
<tr class="odd">
<td>S9</td>
<td>Note that NeuralNet agrees on a negative sign in three of four panels, strengthening the argument that the Investment-panel divergence is noise.</td>
<td>R3</td>
<td>Add a parenthetical to the neural network discussion.</td>
</tr>
<tr class="even">
<td>S10</td>
<td>Add a legend entry to the forest plot explaining the green colour for Ensemble and Best markers.</td>
<td>R3</td>
<td>Minor visual improvement to Figure 1.</td>
</tr>
</tbody>
</table>
</section>
<section id="blocking-issues-require-re-running-a-notebook" class="level3">
<h3 class="anchored" data-anchor-id="blocking-issues-require-re-running-a-notebook">Blocking issues (require re-running a notebook)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Notebook to fix</th>
<th>Specific action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E1</td>
<td>CLAN label inversion</td>
<td>R2</td>
<td><code>code_build/04_dml_extension.ipynb</code></td>
<td>Swap the mapping so <code>bot_q</code> (lowest CATE) = “most affected” and <code>top_q</code> (highest CATE) = “least affected.” Re-run the notebook, verify corrected JSON, and update paper text if the reported CLAN means change.</td>
</tr>
</tbody>
</table>
</section>
<section id="downgraded-items" class="level3">
<h3 class="anchored" data-anchor-id="downgraded-items">Downgraded items</h3>
<p>None. R2’s E1 is the only issue marked essential across all three reports, and it has clear scientific justification (inverted substantive interpretation). No items were downgraded.</p>
</section>
<section id="referee-disagreements" class="level3">
<h3 class="anchored" data-anchor-id="referee-disagreements">Referee disagreements</h3>
<p>None. All three referees reach the same verdict (minor revision) and agree on the core assessment: replication is successful, the DML extension is well-implemented, and the paper adds genuine value. No referee contradicts another’s findings.</p>
</section>
<section id="already-resolved-suppressed-from-this-round" class="level3">
<h3 class="anchored" data-anchor-id="already-resolved-suppressed-from-this-round">Already resolved (suppressed from this round)</h3>
<p>Not applicable — this is Round 1 with no prior changelogs.</p>
<hr>
<p>RERUN_NEEDED: yes</p>
</section>
</div>
<div id="tabset-1-9" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-9-tab">
<section id="final-review-report" class="level1">
<h1>Final Review Report</h1>
<p><strong>Paper:</strong> The Effect of Corporate Taxes on Investment and Entrepreneurship <strong>Original authors:</strong> Djankov, S., Ganser, T., McLiesh, C., Ramalho, R. and Shleifer, A. (<em>American Economic Journal: Macroeconomics</em>, 2010) <strong>Benchmark:</strong> Baiardi, A. and Naghi, A. A. (<em>Econometrics Journal</em>, 2024) <strong>Rounds completed:</strong> 1 of 3 <strong>Final verdict:</strong> Ready</p>
<hr>
</section>
</div>
<div id="tabset-1-10" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-10-tab">
<p>The original Djankov et al.&nbsp;(2010) paper estimates the effect of corporate tax rates on investment and entrepreneurship using cross-country OLS with 12 controls and roughly 60 observations – a setting where p/N is around 0.2 and OLS is demonstrably inefficient. The DML extension relaxes the linear functional-form assumption on the nuisance functions, allows data-driven variable selection across the 12-dimensional control set, and uses cross-fitting to produce debiased treatment effect estimates. The central finding is that DML recovers larger and statistically significant negative effects where OLS was insignificant: for the primary specification (Investment ~ five-year effective rate), the DML Forest estimate is -0.211 (p = 0.008) compared to OLS -0.189 (p = 0.10). This closely matches the independent Baiardi and Naghi (2024) Forest benchmark of -0.204 (SE = 0.094). Beyond replication and DML, the heterogeneous treatment effect analysis – BLP test, GATE quintiles, and CLAN – is a genuine extension that neither the original paper nor Baiardi and Naghi pursued.</p>
<p><strong>“Would I be pleased to have written this, flaws and all?”</strong> Yes. The replication is essentially exact, the DML extension is methodologically sound and closely matches an independent benchmark, and the HTE analysis adds novel descriptive evidence. The known limitations (small-sample nuisance R-squared, N ~ 60 GATE quintiles) are honestly disclosed and do not undermine the main conclusions.</p>
<hr>
</div>
<div id="tabset-1-11" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-11-tab">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 5%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Specification</th>
<th>Published</th>
<th>Replicated</th>
<th>Delta (%)</th>
<th>N</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Investment ~ 5yr effective rate</td>
<td>-0.189</td>
<td>-0.189</td>
<td>0.13%</td>
<td>61</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>FDI ~ 5yr effective rate</td>
<td>-0.095</td>
<td>-0.095</td>
<td>0.35%</td>
<td>61</td>
<td>PASS</td>
</tr>
<tr class="odd">
<td>Business density ~ 5yr effective rate</td>
<td>-0.070</td>
<td>-0.070</td>
<td>0.69%</td>
<td>60</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>Entry rate ~ 5yr effective rate</td>
<td>-0.133</td>
<td>-0.133</td>
<td>0.23%</td>
<td>50</td>
<td>PASS</td>
</tr>
</tbody>
</table>
<p><strong>Overall:</strong> 4/4 reference specifications replicated within the 5% threshold (worst deviation: 0.69%). All signs correct, all sample sizes match exactly. The replication also ran the full 4 x 3 = 12 OLS regression matrix (four outcomes by three tax measures). This is a clean replication.</p>
<hr>
</div>
<div id="tabset-1-12" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-12-tab">
<p>Primary specification: Investment as % of GDP ~ Five-year effective tax rate (N = 61)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>Coef</th>
<th>SE</th>
<th>95% CI</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS (original)</td>
<td>-0.189</td>
<td>0.116</td>
<td>[-0.416, 0.038]</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>Forest (DML Best)</td>
<td>-0.211</td>
<td>0.079</td>
<td>[-0.366, -0.056]</td>
<td>0.008</td>
</tr>
<tr class="odd">
<td>Boosting (DML)</td>
<td>-0.234</td>
<td>0.105</td>
<td>[-0.440, -0.028]</td>
<td>0.02</td>
</tr>
<tr class="even">
<td>ElasticNet (DML)</td>
<td>-0.201</td>
<td>0.091</td>
<td>[-0.379, -0.017]</td>
<td>0.03</td>
</tr>
<tr class="odd">
<td>Lasso (DML)</td>
<td>-0.238</td>
<td>0.130</td>
<td>[-0.493, 0.017]</td>
<td>0.07</td>
</tr>
<tr class="even">
<td>Ensemble (DML)</td>
<td>-0.148</td>
<td>0.121</td>
<td>[-0.385, 0.089]</td>
<td>0.22</td>
</tr>
<tr class="odd">
<td>B&amp;N benchmark (Forest)</td>
<td>-0.204</td>
<td>0.094</td>
<td>–</td>
<td>–</td>
</tr>
</tbody>
</table>
<p><strong>Key finding:</strong> DML with Random Forest recovers a treatment effect 12% larger than OLS and achieves significance at the 1% level where OLS cannot reject zero. Five of six learners agree on a negative sign; the neural network diverges (+0.063, p = 0.61), which is expected small-sample noise and does not recur in the other three panels. The 3.4% difference between our Forest estimate (-0.211) and the Baiardi and Naghi benchmark (-0.204) validates the pipeline implementation.</p>
<hr>
</div>
<div id="tabset-1-13" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-13-tab">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 31%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Raised (round)</th>
<th>Category</th>
<th>Resolved?</th>
<th>How</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E1: CLAN label inversion (most/least affected groups swapped in code)</td>
<td>1 (R2)</td>
<td>Essential</td>
<td>Yes</td>
<td>Swapped labels in notebook; re-ran pipeline; updated paper narrative and conclusion</td>
</tr>
<tr class="even">
<td>S1: Selection-on-observables caveat in conclusion</td>
<td>1 (R1)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Two sentences added to conclusion</td>
</tr>
<tr class="odd">
<td>S2: Nuisance R-squared discussion (residual variation + B&amp;N SE penalty)</td>
<td>1 (R1, R3)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Two sentences added to diagnostics discussion</td>
</tr>
<tr class="even">
<td>S3: GATE gradient is descriptive, not causal</td>
<td>1 (R1)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Sentence added to GATE paragraph</td>
</tr>
<tr class="odd">
<td>S4: Increase n_rep from 5 to &gt;= 20</td>
<td>1 (R2)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Current results stable (cross-fit ratio = 0.21); matches benchmark</td>
</tr>
<tr class="even">
<td>S5: Fix Lasso diagnostics extraction</td>
<td>1 (R2)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Pipeline-level fix; no impact on core estimates</td>
</tr>
<tr class="odd">
<td>S6: Clarify “Best” learner selection criterion</td>
<td>1 (R2)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Sentence added to results section</td>
</tr>
<tr class="even">
<td>S7: DecisionTree anomaly in Panel C</td>
<td>1 (R2)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Sentence added to Panel C bullet</td>
</tr>
<tr class="odd">
<td>S8: FDI Lasso p-value precision (0.053 vs 0.05)</td>
<td>1 (R3)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Changed to “marginally significant at p = 0.053”</td>
</tr>
<tr class="even">
<td>S9: NeuralNet cross-panel sign agreement</td>
<td>1 (R3)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Parenthetical added to primary specification paragraph</td>
</tr>
<tr class="odd">
<td>S10: Forest plot legend for green markers</td>
<td>1 (R3)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Visual improvement; no substantive impact</td>
</tr>
</tbody>
</table>
<p>One round was sufficient. The sole essential issue (CLAN label inversion) was corrected and the notebook was re-run. Seven of ten suggestions were addressed in the paper text; three were deferred for defensible reasons.</p>
<hr>
</div>
<div id="tabset-1-14" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-14-tab">
<p>No essential issues remain. The paper is ready to share. The suggestions below would strengthen it further but are optional.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 29%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Item</th>
<th>Category</th>
<th>Action needed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>n_rep = 5 (below the recommended &gt;= 20)</td>
<td>Suggestion</td>
<td>Increase to 20 if computationally feasible; current results are stable and match the benchmark, so this is not urgent</td>
</tr>
<tr class="even">
<td>2</td>
<td>Lasso variable selection diagnostics are null</td>
<td>Suggestion</td>
<td>Fix the <code>extract_lasso_diagnostics</code> function at the pipeline level; add a footnote in the paper noting the limitation</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Forest plot lacks legend entry for green Ensemble/Best markers</td>
<td>Suggestion</td>
<td>Add legend to Figure 1 for standalone interpretability</td>
</tr>
</tbody>
</table>
<p><em>Category: <strong>Essential</strong> = must fix before sharing. <strong>Suggestion</strong> = would improve, optional.</em></p>
<hr>
</div>
<div id="tabset-1-15" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-15-tab">
<ul>
<li><p><strong>The RECAST confirms the original finding.</strong> Higher corporate taxes are associated with lower investment and entrepreneurship. DML strengthens this conclusion by recovering larger and statistically significant negative effects across all four outcomes, particularly for the primary specification where OLS was insignificant.</p></li>
<li><p><strong>Identification is selection-on-observables throughout.</strong> Neither OLS nor DML resolves potential endogeneity from omitted confounders (e.g., political institutions that jointly determine tax policy and investment climate). The paper now states this explicitly in the conclusion. Readers should not interpret the DML results as stronger causal evidence than the original OLS – the gain is in efficiency and robustness to functional form, not in identification.</p></li>
<li><p><strong>The nuisance model quality flag (FAIL) is a known small-sample limitation, not a fatal flaw.</strong> Average cross-validated R-squared is negative because most ML learners overfit with N ~ 60 and 12 controls. The best learner (Random Forest) achieves positive R-squared (0.051 for outcome, 0.090 for treatment), the cross-fit stability ratio is low (0.21), and the estimate matches the independent benchmark. The B&amp;N adjusted SE formula already penalizes unstable nuisance estimation.</p></li>
<li><p><strong>The heterogeneous treatment effect results are exploratory.</strong> With quintiles of approximately 12 observations each, the GATE gradient (-1.72 to +1.34) is descriptive rather than precisely estimated. The CLAN finding that trade openness correlates with larger negative effects is economically suggestive but should not be over-interpreted without a larger sample or additional identification strategy.</p></li>
<li><p><strong>Manual check recommended before citing specific CLAN means.</strong> The CLAN labels were corrected in Round 1 (the original code had “most” and “least” affected swapped). The corrected JSON now shows no statistically significant CLAN differences at the 10% level for any control variable, including trade freedom (p = 0.21). The paper text reports means of 7.52 vs.&nbsp;6.72 for trade freedom, but the corrected JSON records 7.38 vs.&nbsp;6.87. This small discrepancy likely reflects the pre-correction vs.&nbsp;post-correction values; verify the paper’s CLAN numbers match the final <code>hte_results.json</code> before treating them as definitive.</p></li>
</ul>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/qgallea\.github\.io\/recast-causal-ai");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>RECAST</strong> by <a href="https://thecausalmindset.com">Quentin Gallea, Ph.D.</a> · Built with <a href="https://claude.ai/code">Claude Code</a> &amp; <a href="https://quarto.org">Quarto</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/qgallea/recast-causal-ai">GitHub</a> · <a href="https://thecausalmindset.com/training/claude-code-for-research">Claude Code for Research</a></p>
</div>
  </div>
</footer>




</body></html>