<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>final_report – RECAST</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-e57afe155632aaa660b5c675715ddaef.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">RECAST</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../papers.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../submissions.html"> 
<span class="menu-text">Tracker</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../submit.html"> 
<span class="menu-text">Submit</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../framework.html"> 
<span class="menu-text">Framework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/qgallea/recast-causal-ai"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#final-review-report" id="toc-final-review-report" class="nav-link active" data-scroll-target="#final-review-report">Final Review Report</a>
  <ul class="collapse">
  <li><a href="#overall-assessment" id="toc-overall-assessment" class="nav-link" data-scroll-target="#overall-assessment">Overall Assessment</a></li>
  <li><a href="#what-was-solved-during-revision" id="toc-what-was-solved-during-revision" class="nav-link" data-scroll-target="#what-was-solved-during-revision">What Was Solved During Revision</a></li>
  <li><a href="#remaining-issues" id="toc-remaining-issues" class="nav-link" data-scroll-target="#remaining-issues">Remaining Issues</a></li>
  <li><a href="#key-results" id="toc-key-results" class="nav-link" data-scroll-target="#key-results">Key Results</a></li>
  <li><a href="#notes-for-the-reader" id="toc-notes-for-the-reader" class="nav-link" data-scroll-target="#notes-for-the-reader">Notes for the Reader</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>



<div class="construction-banner">
<p>🚧 <strong>Under construction &amp; testing</strong> — This site is in active development. Results have not been independently verified. Do not cite or rely on any output without manual review.</p>
</div>
<section id="final-review-report" class="level1">
<h1>Final Review Report</h1>
<p><strong>Paper:</strong> The Effect of Corporate Taxes on Investment and Entrepreneurship <strong>Original authors:</strong> Djankov, S., Ganser, T., McLiesh, C., Ramalho, R. and Shleifer, A. (<em>American Economic Journal: Macroeconomics</em>, 2010) <strong>Rounds completed:</strong> 1 of 3 <strong>Final verdict:</strong> Minor manual revision needed</p>
<hr>
<section id="overall-assessment" class="level2">
<h2 class="anchored" data-anchor-id="overall-assessment">Overall Assessment</h2>
<p>This RECAST of Djankov et al.&nbsp;(2010) replicates the full 12-specification matrix from the original paper’s Table 5D (4 outcomes x 3 tax measures) and extends each specification with a DoubleML Partial Linear Regression using four ML learners. The replication is partially successful: all 12 OLS coefficients have the correct negative sign, and one of the four benchmarkable specifications (Entry rate, Panel D) replicates within the 20% threshold (3.5% deviation). The other three benchmarkable specifications deviate by 27.9% to 177.9%, driven by a sample-size gap (N = 42-53 in our data vs.&nbsp;50-61 in the reference) that appears to reflect non-random missingness in institutional control variables.</p>
<p>The DML extension delivers genuine value for three of the four outcome panels. For FDI (Panel B), business density (Panel C), and entry rate (Panel D), all four ML learners agree on the negative sign, and multiple learners produce statistically significant estimates where OLS does not – the clearest gain being in Panel D, where Gradient Boosting yields -0.228 (p = 0.002) compared to OLS -0.128 (p = 0.34). For Investment/GDP (Panel A), however, the DML extension is uninformative: two learners flip sign, nuisance R-squared values are deeply negative, and the automated preferred-learner selection (LassoCV) produces a near-zero, sign-reversed coefficient of +0.010 (p = 0.94). The paper’s revised text correctly flags this.</p>
<p>Would this be publishable as a short note? In its current form, close. The core finding – that DML recovers significant negative tax effects in three of four panels where OLS is insignificant under kitchen-sink controls – is a genuine contribution that extends Baiardi &amp; Naghi (2024). The identification discussion, after revision, is honest about the limits of both OLS and DML in this cross-country setting. The remaining issues are minor and manageable with a careful manual pass.</p>
<hr>
</section>
<section id="what-was-solved-during-revision" class="level2">
<h2 class="anchored" data-anchor-id="what-was-solved-during-revision">What Was Solved During Revision</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 34%">
<col style="width: 40%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Raised (round)</th>
<th>Resolved (round)</th>
<th>How</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Estimand undefined; causal vs.&nbsp;associational language inconsistent</td>
<td>1</td>
<td>1</td>
<td>Added formal estimand definition (Eq. 1) and consistent language policy</td>
</tr>
<tr class="even">
<td>Selection-on-observables not defended; DML does not solve OVB</td>
<td>1</td>
<td>1</td>
<td>Added “Threats to identification” paragraph and DML caveat in Section 3.1</td>
</tr>
<tr class="odd">
<td>Panel A Lasso/ElasticNet flagged as unreliable</td>
<td>1</td>
<td>1</td>
<td>Rewrote Panel A bullet; italicised warning on Lasso/ElasticNet estimates</td>
</tr>
<tr class="even">
<td>Panel C replication deviation (177.9%) underexplained</td>
<td>1</td>
<td>1</td>
<td>Added dedicated paragraph on influential observations and right-skewed outcome</td>
</tr>
<tr class="odd">
<td>Sample-size discrepancy underexplained</td>
<td>1</td>
<td>1</td>
<td>Identified specific controls causing missingness; noted non-random attrition</td>
</tr>
<tr class="even">
<td>“DML strengthens” language too strong given negative nuisance R-squared</td>
<td>1</td>
<td>1</td>
<td>Replaced with “broadly consistent with” and “supportive, though not dispositive”</td>
</tr>
<tr class="odd">
<td>Best-learner selection by p-value introduces selection bias</td>
<td>1</td>
<td>1</td>
<td>Added paragraph and footnote documenting the criterion and its limitation</td>
</tr>
<tr class="even">
<td>GATE grouping variable unjustified</td>
<td>1</td>
<td>1</td>
<td>Added justification and exploratory-analysis caveat</td>
</tr>
<tr class="odd">
<td>N_rep = 3 limitation</td>
<td>1</td>
<td>1</td>
<td>Noted as limitation; recommended N_rep = 5-10</td>
</tr>
<tr class="even">
<td>K = 5 borderline for Panel D</td>
<td>1</td>
<td>1</td>
<td>Noted in diagnostics; suggested K = 3 robustness check</td>
</tr>
<tr class="odd">
<td>CATE summary statistics ambiguous</td>
<td>1</td>
<td>1</td>
<td>Clarified as smoothed conditional effects, not unit-level heterogeneity</td>
</tr>
<tr class="even">
<td>HC1 vs.&nbsp;DML SEs not distinguished</td>
<td>1</td>
<td>1</td>
<td>Added explanation of Neyman-orthogonal score derivation</td>
</tr>
<tr class="odd">
<td>Missing reference values for 8/12 specs</td>
<td>1</td>
<td>1</td>
<td>Prominently flagged in replication assessment</td>
</tr>
<tr class="even">
<td>Forest plot omits published estimates</td>
<td>1</td>
<td>1</td>
<td>Added published values in figure caption</td>
</tr>
<tr class="odd">
<td>Missing robustness checks</td>
<td>1</td>
<td>1</td>
<td>Acknowledged as limitation; listed desirable checks</td>
</tr>
<tr class="even">
<td>Panel D sample drop needs identification comment</td>
<td>1</td>
<td>1</td>
<td>Addressed jointly with sample-size discrepancy</td>
</tr>
</tbody>
</table>
<p>All 7 major and 9 minor issues from round 1 were resolved through prose edits. No notebook re-runs were required.</p>
<hr>
</section>
<section id="remaining-issues" class="level2">
<h2 class="anchored" data-anchor-id="remaining-issues">Remaining Issues</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Severity</th>
<th>Action needed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Panel C replication deviation (177.9%) has no formal diagnostic. The paper discusses influential-observation risk but no Cook’s distance or DFBETAS analysis was run.</td>
<td>Major</td>
<td>Run leverage diagnostics on Panel C (Business density ~ effective_5yr) manually. Identify which of the 7 missing countries are high-leverage and report whether the -0.195 estimate is driven by one or two observations.</td>
</tr>
<tr class="even">
<td>2</td>
<td>Preferred-learner designation in <code>dml_results.json</code> still reports LassoCV with <code>preferred_coef: 0.010</code> for the primary specification (Panel A, effective_5yr). The paper text overrides this narratively but the metadata is misleading.</td>
<td>Minor</td>
<td>Update <code>preferred_learner</code> and <code>preferred_coef</code> in <code>dml_results.json</code> to reflect Random Forest (-0.118) for the primary specification, or add a <code>narrative_preferred</code> field.</td>
</tr>
<tr class="odd">
<td>3</td>
<td>No reduced-control specification was tested. With N = 42-53 and 12 controls, a specification with fewer controls (e.g., dropping the 3-4 variables with the most missingness) would recover a larger sample and test robustness.</td>
<td>Minor</td>
<td>Run a supplementary OLS and DML with 8 controls (dropping emplo_i2004, legalform, avinformal3, seign2004) as a robustness check.</td>
</tr>
<tr class="even">
<td>4</td>
<td>Causal forest extension was configured in config.yaml (<code>enabled: true</code>) but <code>causal_forest_results.json</code> does not exist. The causal forest stage was never executed.</td>
<td>Minor</td>
<td>Either run <code>/recast-cf</code> to produce the causal forest analysis, or set <code>enabled: false</code> in config.yaml to avoid confusion.</td>
</tr>
</tbody>
</table>
<p><em>Severity: <strong>Blocking</strong> = must fix before sharing. <strong>Major</strong> = should fix. <strong>Minor</strong> = optional.</em></p>
<hr>
</section>
<section id="key-results" class="level2">
<h2 class="anchored" data-anchor-id="key-results">Key Results</h2>
<section id="primary-specification-panel-a-investment-five-year-effective-rate" class="level3">
<h3 class="anchored" data-anchor-id="primary-specification-panel-a-investment-five-year-effective-rate">Primary specification (Panel A: Investment ~ five-year effective rate)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 25%">
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>Specification</th>
<th>Estimate</th>
<th>SE</th>
<th>95% CI</th>
<th>N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Published OLS (Djankov et al.&nbsp;2010)</td>
<td>-0.189</td>
<td>0.118</td>
<td>[-0.420, 0.042]</td>
<td>61</td>
</tr>
<tr class="even">
<td>Published DML Lasso (Baiardi &amp; Naghi 2024)</td>
<td>-0.178</td>
<td>0.096</td>
<td>[-0.366, 0.010]</td>
<td>61</td>
</tr>
<tr class="odd">
<td>Our replication (OLS, HC1)</td>
<td>-0.089</td>
<td>0.145</td>
<td>[-0.372, 0.195]</td>
<td>53</td>
</tr>
<tr class="even">
<td>DML LassoCV (preferred by pipeline)</td>
<td>+0.010</td>
<td>0.135</td>
<td>[-0.256, 0.275]</td>
<td>53</td>
</tr>
<tr class="odd">
<td>DML Random Forest (substantively preferred)</td>
<td>-0.118</td>
<td>0.084</td>
<td>[-0.282, 0.047]</td>
<td>53</td>
</tr>
<tr class="even">
<td>DML Gradient Boosting</td>
<td>-0.132</td>
<td>0.107</td>
<td>[-0.321, 0.078]</td>
<td>53</td>
</tr>
</tbody>
</table>
<p><strong>Replication check:</strong> FAIL – 53.0% relative deviation vs.&nbsp;published OLS for Panel A (worst deviation: 177.9% for Panel C). Only 1/4 benchmarkable specs within 20% threshold (Panel D: 3.5%).</p>
<p><strong>DML shift (Panel A):</strong> The tree-based DML estimates (RF: -0.118, GBM: -0.132) are smaller in magnitude than the published OLS (-0.189) but preserve the negative sign. The linear DML estimates (Lasso: +0.010, ElasticNet: +0.027) flip sign and are unreliable due to deeply negative nuisance R-squared. The DML extension is uninformative for Panel A.</p>
</section>
<section id="strongest-dml-results-panels-b-d" class="level3">
<h3 class="anchored" data-anchor-id="strongest-dml-results-panels-b-d">Strongest DML results (Panels B-D)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th>Panel</th>
<th>Outcome</th>
<th>Treatment</th>
<th>OLS (ours)</th>
<th>Best DML</th>
<th>Learner</th>
<th>p-value</th>
<th>N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>B</td>
<td>FDI/GDP</td>
<td>Effective 1yr</td>
<td>-0.131 (p=0.05)</td>
<td>-0.187</td>
<td>ElasticNet</td>
<td>0.010</td>
<td>53</td>
</tr>
<tr class="even">
<td>B</td>
<td>FDI/GDP</td>
<td>Effective 5yr</td>
<td>-0.121 (p=0.19)</td>
<td>-0.148</td>
<td>ElasticNet</td>
<td>0.050</td>
<td>53</td>
</tr>
<tr class="odd">
<td>C</td>
<td>Business density</td>
<td>Effective 1yr</td>
<td>-0.199 (p=0.07)</td>
<td>-0.265</td>
<td>LassoCV</td>
<td>0.004</td>
<td>53</td>
</tr>
<tr class="even">
<td>C</td>
<td>Business density</td>
<td>Effective 5yr</td>
<td>-0.195 (p=0.07)</td>
<td>-0.247</td>
<td>LassoCV</td>
<td>0.005</td>
<td>53</td>
</tr>
<tr class="odd">
<td>D</td>
<td>Entry rate</td>
<td>Statutory</td>
<td>-0.139 (p=0.12)</td>
<td>-0.184</td>
<td>RandomForest</td>
<td>0.001</td>
<td>42</td>
</tr>
<tr class="even">
<td>D</td>
<td>Entry rate</td>
<td>Effective 5yr</td>
<td>-0.128 (p=0.34)</td>
<td>-0.228</td>
<td>GradientBoosting</td>
<td>0.002</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>DML shift (Panels B-D):</strong> The DML estimates are consistently larger in magnitude than OLS by 15-78% and reach statistical significance in many specifications where OLS does not. This pattern is consistent across learners and panels: all four DML learners agree on the negative sign for all 9 specifications in Panels B-D. The strongest gains are in Panel D (Entry rate), where DML estimates are roughly 30-60% larger than OLS and highly significant.</p>
<hr>
</section>
</section>
<section id="notes-for-the-reader" class="level2">
<h2 class="anchored" data-anchor-id="notes-for-the-reader">Notes for the Reader</h2>
<ul>
<li><p><strong>Identification is inherited, not improved.</strong> DML relaxes functional-form assumptions on the nuisance functions but requires the same conditional-independence (selection-on-observables) assumption as OLS. The original paper acknowledges omitted-variable concerns (GDP per capita, government expenditure, tax competition). The DML extension does not resolve these; it only addresses the problem that 12 controls in a sample of ~50 countries may introduce functional-form misspecification under OLS.</p></li>
<li><p><strong>Nuisance model quality is poor throughout.</strong> Average out-of-sample R-squared for both the outcome and treatment nuisance models is negative across all learners. This means the ML models predict worse than the sample mean. Under these conditions, DML standard errors may not satisfy the regularity conditions for asymptotic validity, and the reported p-values should be treated as indicative rather than exact. The consistent sign pattern across learners in Panels B-D is more informative than any individual p-value.</p></li>
<li><p><strong>The 177.9% replication deviation in Panel C is unresolved at a formal level.</strong> The paper discusses influential-observation risk qualitatively but no leverage diagnostics have been run. Before citing the Panel C results, a manual check (Cook’s distance or leave-one-out) is needed to determine whether the large replicated coefficient (-0.195 vs.&nbsp;published -0.070) reflects genuine signal or a handful of influential countries in the reduced sample.</p></li>
<li><p><strong>Sample-size loss is non-trivial.</strong> Our data yields N = 42-53 vs.&nbsp;50-61 in the reference, a 13-18% reduction. The missingness is concentrated in institutional control variables (employment rigidity, legal formalism, average informality) that vary with development level, so the dropped countries are likely systematically different from those retained. This non-random attrition could bias results in either direction.</p></li>
<li><p><strong>The pipeline cannot verify data provenance or variable construction.</strong> The replication uses <code>data_taxes.csv</code> as provided. Whether this exactly matches the original Djankov et al.&nbsp;(2010) dataset, or whether variable definitions (e.g., “five-year effective rate”) are computed identically to the original paper, cannot be confirmed without access to the original authors’ code and data files.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/qgallea\.github\.io\/recast-causal-ai");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>RECAST</strong> by <a href="https://thecausalmindset.com">Quentin Gallea, Ph.D.</a> · Built with <a href="https://claude.ai/code">Claude Code</a> &amp; <a href="https://quarto.org">Quarto</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/qgallea/recast-causal-ai">GitHub</a> · <a href="https://thecausalmindset.com/training/claude-code-for-research">Claude Code for Research</a></p>
</div>
  </div>
</footer>




</body></html>