<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nunn &amp; Trefler">
<meta name="dcterms.date" content="2010-01-01">
<meta name="description" content="Cross-country OLS: do skill-biased tariffs promote long-term economic growth?">

<title>The Structure of Tariffs and Long-term Growth – RECAST</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6cd8083c2b52a75285f27e87131d3d27.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  var banner = document.createElement('div');
  banner.className = 'construction-banner';
  banner.innerHTML = '&#x1F6A7; <strong>Under construction &amp; testing</strong> &mdash; This site is in active development. Results have not been independently verified. Do not cite or rely on any output without manual review.';
  document.body.insertBefore(banner, document.body.firstChild);
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">RECAST</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../papers.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../framework.html"> 
<span class="menu-text">Framework</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../submissions.html"> 
<span class="menu-text">Tracker</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../submit.html"> 
<span class="menu-text">Submit</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/qgallea/recast-causal-ai"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#paper-summary" id="toc-paper-summary" class="nav-link active" data-scroll-target="#paper-summary">Paper summary</a></li>
  <li><a href="#replication-results" id="toc-replication-results" class="nav-link" data-scroll-target="#replication-results">Replication results</a></li>
  <li><a href="#dml-extension" id="toc-dml-extension" class="nav-link" data-scroll-target="#dml-extension">DML Extension</a></li>
  <li><a href="#what-did-causal-ml-add-here" id="toc-what-did-causal-ml-add-here" class="nav-link" data-scroll-target="#what-did-causal-ml-add-here">What did causal ML add here?</a></li>
  <li><a href="#referee-reports" id="toc-referee-reports" class="nav-link" data-scroll-target="#referee-reports">Referee reports</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The Structure of Tariffs and Long-term Growth</h1>
  <div class="quarto-categories">
    <div class="quarto-category">OLS</div>
    <div class="quarto-category">Trade</div>
    <div class="quarto-category">Growth</div>
    <div class="quarto-category">2010</div>
    <div class="quarto-category">PASS</div>
  </div>
  </div>

<div>
  <div class="description">
    Cross-country OLS: do skill-biased tariffs promote long-term economic growth?
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nunn &amp; Trefler </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">2010</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="paper-summary" class="level2">
<h2 class="anchored" data-anchor-id="paper-summary">Paper summary</h2>
<p><strong>Citation:</strong> Nunn, N. &amp; Trefler, D. (2010). “The Structure of Tariffs and Long-term Growth.” <em>American Economic Journal: Macroeconomics</em>, 2(3), 158–94. <a href="https://doi.org/10.1257/mac.2.3.158">DOI</a></p>
<p><strong>Identification strategy:</strong> Cross-country OLS regressions estimating the relationship between the skill-bias of tariffs and long-term economic growth. The paper uses three measures of skill-biased tariffs — skill tariff correlation, and two tariff differential measures with different cut-offs — and regresses them on log annual per capita GDP growth with 17 control variables including average tariff level, initial conditions, human capital, regional dummies, and time dummies. N = 63 countries.</p>
<p><strong>Key original result:</strong> Skill-biased tariffs are positively associated with long-term growth. The OLS coefficient on skill tariff correlation is 0.035 (SE 0.010, p &lt; 0.01), suggesting that countries with tariff structures favouring skill-intensive industries experience higher growth.</p>
<p><strong>Reference:</strong> This paper was revisited by <a href="https://doi.org/10.1093/ectj/utae004">Baiardi &amp; Naghi (2024, <em>Econometrics Journal</em>)</a>, who applied DML and found considerably smaller, often insignificant effects — suggesting the OLS result is not robust to flexible nonlinear controls.</p>
<hr>
</section>
<section id="replication-results" class="level2">
<h2 class="anchored" data-anchor-id="replication-results">Replication results</h2>
<p>The replication is <strong>successful</strong>. All 3 OLS coefficients match the Baiardi &amp; Naghi (2024) reference closely. Sample sizes match exactly (N = 63).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Panel</th>
<th>Treatment</th>
<th>Published</th>
<th>Replicated</th>
<th>Δ (%)</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>Skill tariff correlation</td>
<td>0.035</td>
<td>0.035</td>
<td>0.46%</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>B</td>
<td>Tariff differential (low)</td>
<td>0.016</td>
<td>0.016</td>
<td>1.64%</td>
<td>PASS</td>
</tr>
<tr class="odd">
<td>C</td>
<td>Tariff differential (high)</td>
<td>0.020</td>
<td>0.019</td>
<td>5.11%</td>
<td>PASS</td>
</tr>
</tbody>
</table>
<p><em>Panel C’s 5.11% deviation is a rounding artefact — the published 0.020 rounds from 0.019.</em></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="forest_plot.png" class="img-fluid figure-img"></p>
<figcaption>Forest plot: OLS vs.&nbsp;DML estimates across methods</figcaption>
</figure>
</div>
<hr>
</section>
<section id="dml-extension" class="level2">
<h2 class="anchored" data-anchor-id="dml-extension">DML Extension</h2>
<p>Double/Debiased Machine Learning was applied using the <strong>PLR</strong> model with K=2 folds, 20 repetitions (median aggregation, B&amp;N adjusted SE), and 6 ML methods + Ensemble + Best.</p>
<section id="key-results-panel-a-skill-tariff-correlation" class="level3">
<h3 class="anchored" data-anchor-id="key-results-panel-a-skill-tariff-correlation">Key results (Panel A: skill tariff correlation)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>Coef</th>
<th>SE</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS</td>
<td>0.035***</td>
<td>0.010</td>
<td>0.001</td>
</tr>
<tr class="even">
<td>Lasso</td>
<td>0.020</td>
<td>0.013</td>
<td>0.137</td>
</tr>
<tr class="odd">
<td>Decision Tree</td>
<td>0.013</td>
<td>0.011</td>
<td>0.237</td>
</tr>
<tr class="even">
<td>Boosting</td>
<td>0.020</td>
<td>0.012</td>
<td>0.111</td>
</tr>
<tr class="odd">
<td>Random Forest</td>
<td>0.018</td>
<td>0.011</td>
<td>0.095*</td>
</tr>
<tr class="even">
<td>Ensemble</td>
<td>0.019</td>
<td>0.012</td>
<td>0.124</td>
</tr>
<tr class="odd">
<td><strong>Best (Boosting)</strong></td>
<td><strong>0.020</strong></td>
<td><strong>0.012</strong></td>
<td><strong>0.111</strong></td>
</tr>
</tbody>
</table>
<p><em>Best learner selected by lowest nuisance MSE. NeuralNet excluded (catastrophic R² = −38.8).</em></p>
<p><strong>Key finding:</strong> DML estimates are <strong>40–55% smaller than OLS</strong> across all three treatment measures and all well-behaved learners. The positive sign is preserved but statistical significance is lost — only Forest reaches marginal significance (p = 0.095). This means the tariff–growth relationship is <strong>not robust to controlling for nonlinear confounders</strong>, confirming Baiardi &amp; Naghi’s (2024) finding.</p>
</section>
<section id="heterogeneous-treatment-effects" class="level3">
<h3 class="anchored" data-anchor-id="heterogeneous-treatment-effects">Heterogeneous treatment effects</h3>
<p><strong>BLP test:</strong> β₂ = 1.08 (p &lt; 0.001) — <strong>strongly significant heterogeneity</strong>.</p>
<p><strong>GATE analysis</strong> (5 quintiles of predicted CATE) reveals a striking gradient: skill-biased tariffs <strong>harm</strong> growth in some countries (Q1: −0.206) while <strong>helping</strong> in others (Q5: +0.235). The average effect masks substantial opposing effects.</p>
<p><strong>CLAN analysis:</strong> Only investment (<code>inv</code>) is marginally different between most- and least-affected groups (p = 0.074).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="gate_plot.png" class="img-fluid figure-img"></p>
<figcaption>GATE estimates by quintile</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="what-did-causal-ml-add-here" class="level2">
<h2 class="anchored" data-anchor-id="what-did-causal-ml-add-here">What did causal ML add here?</h2>
<p>This is one of the most informative RECAST applications. The DML extension reveals two important findings absent from the original paper:</p>
<ol type="1">
<li><p><strong>The OLS effect is inflated.</strong> When nonlinear confounding is flexibly controlled via DML, the skill-biased tariff coefficient shrinks by 40–55% and loses significance. This suggests the original OLS estimate captures correlations with nonlinear confounders (regional effects, institutional quality) rather than a pure tariff effect. Baiardi &amp; Naghi (2024) reach the same conclusion.</p></li>
<li><p><strong>The average masks opposing effects.</strong> The BLP test strongly rejects homogeneous effects (p &lt; 0.001), and the GATE gradient from −0.206 to +0.235 shows that skill-biased tariffs have sharply different consequences depending on country characteristics. This finding was not explored in the original paper and adds genuine policy relevance: one-size-fits-all tariff policy recommendations may be misleading.</p></li>
</ol>
<p>The main limitation is low nuisance model R² (outcome: 0.15, treatment: 0.36), inherent to the small sample (N = 63, p = 17). Despite this, the qualitative conclusions are consistent across all well-behaved learners and match the independent B&amp;N benchmark.</p>
<hr>
</section>
<section id="referee-reports" class="level2">
<h2 class="anchored" data-anchor-id="referee-reports">Referee reports</h2>
<p><strong>Referee consensus:</strong> All three referees gave “Minor revision.” Two blocking issues (n_rep=5 override, Best learner bug) were found and fixed in Round 1. <strong>Final verdict: Ready.</strong></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Identification</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">Referee 1 Report: Identification</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">DML Methods</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Referee 2 Report: DML Methods &amp; Causal Forest</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href="">Robustness</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false" href="">Referee 3 Report: Robustness and Replication</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-7-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-7" role="tab" aria-controls="tabset-1-7" aria-selected="false" href="">Synthesis</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-8-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-8" role="tab" aria-controls="tabset-1-8" aria-selected="false" href="">Synthesis Report – Round 1</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-9-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-9" role="tab" aria-controls="tabset-1-9" aria-selected="false" href="">Final Report</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-10-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-10" role="tab" aria-controls="tabset-1-10" aria-selected="false" href="">What This RECAST Contributes</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-11-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-11" role="tab" aria-controls="tabset-1-11" aria-selected="false" href="">Replication Summary</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-12-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-12" role="tab" aria-controls="tabset-1-12" aria-selected="false" href="">DML Extension Summary</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-13-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-13" role="tab" aria-controls="tabset-1-13" aria-selected="false" href="">Heterogeneity Summary</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-14-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-14" role="tab" aria-controls="tabset-1-14" aria-selected="false" href="">Review Process Summary</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-15-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-15" role="tab" aria-controls="tabset-1-15" aria-selected="false" href="">Remaining Items</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-16-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-16" role="tab" aria-controls="tabset-1-16" aria-selected="false" href="">Notes for the Reader</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">

</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor revision</p>
<section id="contribution-assessment" class="level3">
<h3 class="anchored" data-anchor-id="contribution-assessment">Contribution assessment</h3>
<p>This RECAST adds genuine value to Nunn &amp; Trefler (2010). The original paper relies on OLS with 17 controls in a sample of only 63 countries, making it vulnerable to regularisation bias and functional-form misspecification. The DML extension relaxes the linearity assumption on the nuisance functions, provides data-driven variable selection via Lasso (retaining only 3 of 17 controls for the outcome equation), and delivers an independent robustness check that closely replicates the Baiardi &amp; Naghi (2024) benchmarks (within 0.001–0.002 across all three treatments). The heterogeneous treatment effect analysis is a substantive new contribution: the BLP test and GATE estimates reveal that the original paper’s uniform positive conclusion masks a gradient from significantly negative effects (Q1: -0.206) to significantly positive effects (Q5: +0.193), a finding absent from the original work.</p>
</section>
<section id="essential-issues-must-be-addressed-paper-is-unpublishable-without-these" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues-must-be-addressed-paper-is-unpublishable-without-these">Essential issues (must be addressed – paper is unpublishable without these)</h3>
<ol type="1">
<li><p><strong>The estimand is never formally defined.</strong> The paper uses “ATE” informally (e.g., the BLP proxy is labelled “ATE proxy” in Section 3.2) but never states what the target estimand is – whether the Average Treatment Effect, a conditional expectation, or a partial derivative with respect to a continuous treatment. Because skill1_corr is continuous, the PLR parameter theta is the marginal effect under partial linearity (Y = theta<em>D + g(X) + U), not an ATE in the potential-outcomes sense. Conflating theta with an ATE is substantively misleading, since there is no well-defined “treated” vs.&nbsp;“untreated” state for a continuous measure. This matters especially for the GATE analysis (Section 3.2), where quintile-specific “treatment effects” are reported without clarifying what counterfactual comparison they represent. </em>Action:* Add a short paragraph in Section 3.1 (Method) that formally defines the estimand as the partial linear coefficient theta – the marginal effect of a one-unit increase in the treatment holding X fixed – and distinguish this from the ATE language used in the heterogeneity discussion. In the GATE section, clarify that the “GATE” estimates are group-specific marginal effects derived from the BLP decomposition, not average treatment effects from a binary intervention.</p></li>
<li><p><strong>Low nuisance R-squared is flagged as FAIL but the identification implications are understated.</strong> The diagnostics report R-squared_Y = 0.094 for the outcome nuisance model. The paper correctly notes (Section 4) that Neyman orthogonality protects point estimates from first-order nuisance bias. However, the paper does not acknowledge that when nuisance models explain very little variation, the debiasing step removes very little confounding – meaning the DML estimate may converge toward the unadjusted bivariate coefficient rather than toward a well-controlled causal parameter. In a setting where the whole identification argument rests on selection-on-observables (i.e., adequately conditioning on X), a nuisance model that barely predicts Y|X raises the question of whether the controls are actually doing their job. This is distinct from the standard-error inflation point already made. <em>Action:</em> Add 2–3 sentences in the Diagnostics Discussion (Section 4) acknowledging that low nuisance R-squared may indicate that the ML learners are not effectively capturing the confounding structure in g(X), which limits the debiasing value of DML relative to OLS. Note that external validation against Baiardi &amp; Naghi (2024) partially mitigates this concern but does not resolve it, since their nuisance models face the same small-sample limitation.</p></li>
</ol>
</section>
<section id="suggestions-would-improve-the-paper-but-optional" class="level3">
<h3 class="anchored" data-anchor-id="suggestions-would-improve-the-paper-but-optional">Suggestions (would improve the paper, but optional)</h3>
<ol type="1">
<li><p><strong>Report the bivariate (no-controls) OLS coefficient alongside the 17-control OLS and DML estimates.</strong> If the DML estimate (0.018) is closer to the bivariate OLS than to the 17-control OLS (0.035), this would reinforce the concern that ML nuisance models are not effectively removing confounding. If instead the DML estimate sits between the bivariate and controlled OLS, it would support the interpretation that DML is successfully partialling out at least some confounding. This is a one-line regression that would sharpen the interpretation at negligible cost.</p></li>
<li><p><strong>Discuss the plausibility of selection-on-observables more explicitly.</strong> The original paper’s identification rests on 17 controls being sufficient to close all backdoor paths from tariff skill-bias to growth. The paper currently describes the controls (Section 2.1) but does not discuss potential omitted confounders – for example, institutional quality, trade openness beyond tariffs, or colonial history (beyond regional dummies). A brief paragraph acknowledging the main omitted-variable threats would help the reader assess how much weight to place on the causal interpretation, whether OLS or DML.</p></li>
<li><p><strong>Note that K=2 cross-fitting folds with N=63 means each fold has only ~32 observations for nuisance estimation.</strong> The paper follows Baiardi &amp; Naghi (2024) in using K=2, which is standard in the DML literature, but with N=63 this leaves very few observations per fold for training flexible ML models. Mentioning this as a contributing factor to the low nuisance R-squared would help the reader understand why the ML models underperform.</p></li>
</ol>
</section>
<section id="comments-to-the-authors" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors">Comments to the authors</h3>
<p>The paper is well structured and clearly written. The replication is convincing – all three specifications match the original within rounding tolerance, and the systematic comparison across five ML learners plus external validation against Baiardi &amp; Naghi (2024) is a strength. The heterogeneity analysis is the most interesting contribution: the GATE gradient from -0.206 to +0.193 is a genuinely new finding that enriches the original paper’s blanket positive conclusion. The honest acknowledgment of the Neural Network’s failure (catastrophic R-squared of -38.8) and the transparent diagnostics table are also commendable.</p>
<p>The two essential issues above are narrowly scoped. The estimand clarification (Issue 1) requires only a paragraph of text and no new computation. The nuisance R-squared discussion (Issue 2) requires 2–3 additional sentences. Neither demands re-running any code. With these addressed, the identification discussion would be appropriately careful for a paper whose entire value proposition is “what happens when we relax OLS assumptions” – the reader needs to understand precisely what DML does and does not buy in a setting with N=63 and 17 controls.</p>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">

</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor revision</p>
<section id="methodological-contribution" class="level3">
<h3 class="anchored" data-anchor-id="methodological-contribution">Methodological contribution</h3>
<p>The DML extension is well-suited to this setting. Nunn and Trefler (2010) use OLS with 17 controls in a sample of only 63 countries (<span class="math inline">\(p/N \approx 0.27\)</span>), making regularisation bias a first-order concern. PLR is the correct model class for continuous treatment with selection-on-observables identification. The comparison of 7 ML methods (5 base + Ensemble + Best) provides genuine evidence about whether the positive tariff–growth relationship survives flexible nonlinear control adjustment — and it does, directionally, though at roughly half the OLS magnitude. The close agreement with Baiardi and Naghi (2024) benchmarks (within 0.001–0.002 across all three treatments) provides strong external validation.</p>
</section>
<section id="essential-issues" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues">Essential issues</h3>
<ol type="1">
<li><p><strong>n_rep = 5 is below the recommended minimum of 20 (Checklist item 3).</strong> The code explicitly overrides the config value (<code>n_rep = 5</code>, line 155: “Override n_rep to 5 for speed”) and the SE formula correctly applies the B&amp;N median-aggregation adjustment. However, with only 5 repetitions the median coefficient and the variance term <span class="math inline">\((\hat\theta_k - \tilde\theta)^2\)</span> in the adjusted SE are estimated from very few draws. This matters because <span class="math inline">\(N = 63\)</span> with <span class="math inline">\(K = 2\)</span> folds means each fold has $$31 observations, so cross-fitting variability can be substantial. <strong>Scientific justification:</strong> With 5 reps, the inter-rep variance component in the adjusted SE is estimated with effectively 4 degrees of freedom. A single aberrant fold split could shift the median coefficient or inflate/deflate the adjusted SE by 20–30%. Since all three primary specifications have CIs that just barely include or exclude zero (p-values in the 0.03–0.20 range), the marginal significance conclusions are sensitive to cross-fitting noise. <strong>Recommended fix:</strong> Re-run with n_rep = 20 (the config default). This is computationally cheap for <span class="math inline">\(N = 63\)</span> and 5 learners. If the point estimates and p-value ordering remain unchanged, the current conclusions are confirmed; if they shift, the paper must update its significance statements.</p></li>
<li><p><strong>“Best” learner copies the Forest result wholesale rather than combining the best-outcome and best-treatment learners (Checklist item 4).</strong> The code (line 520) copies all results from <code>best_outcome_method</code> (Forest for Panel A), including its coefficient and SE. But the <code>best_treatment_method</code> is Lasso for Panel A. In the Baiardi and Naghi (2024) methodology, “Best” should re-fit the PLR using the best outcome learner (Forest) for <code>ml_l</code> and the best treatment learner (Lasso) for <code>ml_m</code>. Instead, the current “Best” is simply the Forest result (Forest for both nuisance equations). <strong>Scientific justification:</strong> The treatment nuisance <span class="math inline">\(R^2\)</span> for Forest is 0.286 vs.&nbsp;0.312 for Lasso (Panel A). Using the wrong treatment learner means the first-stage residualisation of <span class="math inline">\(D\)</span> is suboptimal, which inflates the DML standard error and may attenuate the point estimate. The paper explicitly states “Best learner (Forest for outcome, Lasso for treatment)” but the reported coefficient (0.018) and SE (0.0106) are identical to the Forest row, confirming that the best-treatment learner was not actually used. <strong>Recommended fix:</strong> Re-fit the Best specification using Forest for <code>ml_l</code> and Lasso for <code>ml_m</code>. This requires one additional <code>DoubleMLPLR</code> call per specification.</p></li>
</ol>
</section>
<section id="suggestions" class="level3">
<h3 class="anchored" data-anchor-id="suggestions">Suggestions</h3>
<ol type="1">
<li><p><strong>Ensemble SE is computed as a weighted average of individual SEs (Checklist item 8).</strong> The code (lines 500–501) computes <code>ensemble_se = sum(weights * se)</code>. This is not a valid standard error — it does not account for covariance between learner estimates. The correct approach is either (a) to use the delta method with the stacking covariance matrix, or (b) to report the ensemble as a point estimate only and note that no valid SE is available. The current CIs are therefore unreliable for the Ensemble column, though since the paper’s main conclusions rest on the “Best” learner this is not blocking.</p></li>
<li><p><strong>Low nuisance <span class="math inline">\(R^2\)</span> merits a more structured discussion (Checklist item 6).</strong> The outcome <span class="math inline">\(R^2\)</span> ranges from <span class="math inline">\(-38.8\)</span> (NeuralNet, catastrophic) to <span class="math inline">\(0.19\)</span> (Boosting, Panel B). The paper correctly notes that low <span class="math inline">\(R^2\)</span> inflates SEs without biasing point estimates via Neyman orthogonality, and correctly identifies external validation via B&amp;N. This is adequate but could be strengthened by reporting a table of nuisance <span class="math inline">\(R^2\)</span> values for all learners across all three panels, making transparent which learners achieve positive <span class="math inline">\(R^2\)</span> and which do not.</p></li>
<li><p><strong>NeuralNet should be formally excluded or downweighted in interpretation (Checklist item 6).</strong> The NeuralNet outcome <span class="math inline">\(R^2\)</span> is catastrophic (<span class="math inline">\(-38.8\)</span> to <span class="math inline">\(-44.3\)</span>) across all three panels, meaning its nuisance predictions are worse than a constant. The paper describes this as “unreliable” but still includes NeuralNet in the forest plot and the main results table. A cleaner approach is to report it in a footnote or appendix and note that the Ensemble correctly downweights it (weight 0.5–0.6%).</p></li>
<li><p><strong>BLP implementation uses manual OLS rather than the DoubleML API (Checklist items 10–11).</strong> The code (lines 750–752) constructs the BLP regression manually via <code>sm.OLS(Y_res, X_blp)</code> with HC1 standard errors, rather than using <code>obj_hte.blp()</code>. The manual approach is methodologically valid if the residuals <span class="math inline">\(Y_{res}\)</span> and <span class="math inline">\(D_{res}\)</span> are correctly extracted from the DML object, which appears to be the case (lines 733–734). However, using the built-in API would reduce the risk of implementation error and ensure consistency with the GATE computation.</p></li>
<li><p><strong>CLAN lacks statistical power and could note this more explicitly (Checklist item 13).</strong> CLAN is reported with <span class="math inline">\(N = 13\)</span> per extreme quintile and no covariate reaches significance. The paper mentions this is “expected given the small sample” but could add that with 13 observations per group, a standardised effect of <span class="math inline">\(d \approx 1.1\)</span> would be needed for 80% power, making CLAN essentially uninformative here.</p></li>
<li><p><strong>Cross-fitting stability diagnostic is skipped (Checklist item, diagnostics_flags.json).</strong> The <code>cross_fitting_stability</code> check returns SKIP because <code>per_rep_coefs</code> are not stored in the Best learner. Storing and reporting the per-rep coefficients (trivially available from <code>obj.all_coef</code>) would allow readers to assess fold-split sensitivity, which is particularly relevant at <span class="math inline">\(N = 63\)</span>.</p></li>
</ol>
</section>
<section id="dml-checklist-summary" class="level3">
<h3 class="anchored" data-anchor-id="dml-checklist-summary">DML Checklist Summary</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 33%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Item</th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Model class (PLR)</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>2</td>
<td>K-fold adaptive to N</td>
<td>PASS (K=2 for N=63 &lt; 200)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>n_rep &gt;= 20</td>
<td>ESSENTIAL (n_rep=5, see issue 1)</td>
</tr>
<tr class="even">
<td>4</td>
<td>Best by lowest nuisance MSE</td>
<td>ESSENTIAL (copies outcome-best wholesale, see issue 2)</td>
</tr>
<tr class="odd">
<td>5</td>
<td>&gt;= 5 method classes</td>
<td>PASS (Lasso, Tree, Boosting, Forest, NNet + Ensemble + Best)</td>
</tr>
<tr class="even">
<td>6</td>
<td>Nuisance R2 reported honestly</td>
<td>PASS (reported; see suggestion 2 for improvement)</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Score function appropriate</td>
<td>PASS (default PLR score)</td>
</tr>
<tr class="even">
<td>8</td>
<td>CIs from DML SEs</td>
<td>SUGGESTION (Ensemble SE invalid; Best/individual correct)</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Lasso diagnostics reported</td>
<td>PASS (3/17 and 5/17 non-zero for Panel A)</td>
</tr>
<tr class="even">
<td>10</td>
<td>BLP reported before GATE</td>
<td>PASS (beta2 = 1.083, p &lt; 0.001)</td>
</tr>
<tr class="odd">
<td>11</td>
<td>GATE on predicted CATE quintiles</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>12</td>
<td>Jointly valid GATE CIs</td>
<td>PASS (confint(joint=True) confirmed in code)</td>
</tr>
<tr class="odd">
<td>13</td>
<td>CLAN included</td>
<td>PASS (reported; underpowered as expected)</td>
</tr>
</tbody>
</table>
</section>
<section id="comments-to-the-authors-1" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors-1">Comments to the authors</h3>
<p>The DML implementation is generally sound and produces results that are well-aligned with the Baiardi and Naghi (2024) benchmarks, which is the strongest possible external validation for this paper. The PLR model class is appropriate, K=2 is correct for the small sample, the B&amp;N adjusted SE formula is correctly implemented, and the GATE analysis with jointly valid CIs is properly executed via the DoubleML API. The finding that DML coefficients are roughly half the OLS values across all three treatment measures, with all well-behaved learners agreeing on a positive sign, is a genuinely informative result.</p>
<p>The two essential issues are both fixable with modest computational effort. First, increasing n_rep from 5 to 20 will stabilise the median coefficient and the adjusted SE, which is important because the marginal significance of several specifications (p-values in the 0.05–0.20 range) could shift with different cross-fitting draws. Second, the “Best” learner should combine the best outcome learner (Forest) with the best treatment learner (Lasso) in a single PLR fit, rather than simply copying the Forest row. This discrepancy is visible in the data: the Best and Forest rows in dml_results.json are identical (coef = 0.01764, SE = 0.01058), yet the paper claims “Best” uses Forest for outcome and Lasso for treatment. Fixing this will likely produce a slightly different coefficient and potentially a tighter SE (since Lasso achieves higher treatment <span class="math inline">\(R^2\)</span> than Forest: 0.312 vs.&nbsp;0.286).</p>
<p>Neither issue is likely to change the paper’s qualitative conclusions — the DML estimates will almost certainly remain positive, smaller than OLS, and marginally significant — but they are needed for methodological correctness.</p>
</section>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">

</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<p><strong>Round:</strong> 1 <strong>Overall verdict:</strong> Minor revision</p>
<section id="replication-assessment" class="level3">
<h3 class="anchored" data-anchor-id="replication-assessment">Replication assessment</h3>
<p>The replication is a clear success. All three OLS specifications from Nunn and Trefler (2010) Table 2, Column 8 reproduce with correct signs, correct significance levels, and matching sample sizes (N = 63). The maximum coefficient deviation is 5.11% in Panel C (diffg: replicated 0.019 vs.&nbsp;published 0.020), which is a rounding artefact – the raw replicated coefficient is 0.01898, and the published value 0.020 is itself rounded. The other two panels deviate by only 0.46% (Panel A) and 1.64% (Panel B). This is an essentially perfect replication.</p>
</section>
<section id="essential-issues-1" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues-1">Essential issues</h3>
<p>None – replication is adequate and DML results are well-documented.</p>
</section>
<section id="suggestions-1" class="level3">
<h3 class="anchored" data-anchor-id="suggestions-1">Suggestions</h3>
<ol type="1">
<li><p><strong>Cross-fitting stability not reported.</strong> The diagnostics flag <code>cross_fitting_stability</code> is SKIP because per-repetition coefficients are not stored (<code>per_rep_coefs not available in Best learner</code>). With only n_rep = 5 repetitions and K = 2 folds in a sample of N = 63, cross-fitting instability is a legitimate concern. Reporting the range or standard deviation of the 5 repetition-level point estimates for each learner would strengthen the claim that results are stable. This is a single, targeted check (not make-work) and would directly address the small-sample concern.</p></li>
<li><p><strong>Forest plot title encoding.</strong> The forest plot title displays “skill1_corr at’ growth” with a garbled arrow character. This is a minor rendering issue that should be fixed for readability, e.g., by using a plain ASCII arrow or the Unicode right-arrow.</p></li>
<li><p><strong>Neural Network learner: consider explicit exclusion from the “Best” selector pool.</strong> The paper correctly identifies NeuralNet as unreliable (R2_Y = -38.8, coefficient 0.185 vs.&nbsp;0.018 for other learners). The Ensemble already downweights it to 0.6%. However, the paper could note explicitly that NeuralNet was excluded from “Best” consideration (it was – Best selects Forest/Lasso, not NeuralNet) so readers do not wonder whether its catastrophic nuisance performance could contaminate the preferred estimate.</p></li>
<li><p><strong>Replication table SE comparison.</strong> The published SEs from the original paper are (0.010), (0.006), (0.004) for Panels A-C respectively, while the replicated SEs are (0.012), (0.006), (0.005). The Panel A and Panel C SEs are slightly larger. The table footer notes “HC1 robust standard errors” but the original paper’s SE type is not stated in the replication table’s published column. Adding a note such as “Published SEs as reported in the original; replicated SEs use HC1” would clarify whether the slight SE differences are due to SE type or rounding.</p></li>
</ol>
</section>
<section id="comments-to-the-authors-2" class="level3">
<h3 class="anchored" data-anchor-id="comments-to-the-authors-2">Comments to the authors</h3>
<p>The replication of Nunn and Trefler (2010) is thorough and well-executed. All three treatment specifications reproduce within tight tolerances (0.46%, 1.64%, 5.11%), all signs are correct, and all sample sizes match at N = 63. The 5.11% deviation in Panel C is convincingly explained as a rounding artefact and does not affect any substantive conclusion. The paper deserves credit for a clean, transparent replication.</p>
<p>The DML extension is carefully reported in the Baiardi and Naghi (2024) eight-column format across all three panels, and every number in the LaTeX tables traces correctly to <code>dml_results.json</code>. Specific cross-checks: Panel A Best coefficient 0.018 matches JSON value 0.01764 (correct rounding); Panel B Best 0.008 matches JSON 0.00838; Panel C Best 0.008 matches JSON 0.00844. Significance stars are consistent with the reported p-values in all 24 learner-panel cells I verified. The OLS coefficients in the DML table (0.035, 0.016, 0.019) match the replication table, confirming internal consistency. The close agreement with Baiardi and Naghi benchmarks (within 0.001-0.002 for all three Lasso specifications) provides valuable external validation.</p>
<p>The forest plot correctly displays all eight estimate groups for the primary treatment, with the Neural Network outlier clearly visible and well-separated from the cluster of well-behaved learners. The only issue is the encoding artifact in the title. The plot effectively communicates the main finding: DML estimates are systematically smaller than OLS, with the “Best” learner roughly half the OLS magnitude.</p>
<p>The sole area where improvement would be informative is cross-fitting stability. With K = 2 folds and N = 63, the assignment of observations to folds can materially affect point estimates, and the 5-repetition design was chosen precisely to address this. Reporting the repetition-level spread would close this gap. This is a suggestion, not a blocking concern, because the consistency across four well-behaved learners (Lasso, Tree, Boosting, Forest all in the 0.014-0.027 range for Panel A) already provides indirect evidence of stability.</p>
</section>
</div>
<div id="tabset-1-7" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-7-tab">

</div>
<div id="tabset-1-8" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-8-tab">
<p><strong>Unified verdict:</strong> Minor revision (with two blocking code fixes)</p>
<section id="contribution-consensus" class="level3">
<h3 class="anchored" data-anchor-id="contribution-consensus">Contribution consensus</h3>
<p>All three referees agree that this RECAST adds genuine value to Nunn &amp; Trefler (2010). The core contributions are: (i) a near-perfect replication (max 5.11% deviation, a rounding artefact), (ii) a DML extension showing that OLS estimates are roughly twice the DML magnitudes across all three treatments, closely matching the Baiardi &amp; Naghi (2024) benchmarks, and (iii) a heterogeneous treatment effect analysis revealing a striking GATE gradient from -0.206 (Q1) to +0.193 (Q5), a substantively new finding absent from the original paper. The panel view is that this RECAST adds clear value; the bar for blocking is correspondingly high.</p>
</section>
<section id="essential-issues-must-be-addressed-paper-cannot-stand-as-is" class="level3">
<h3 class="anchored" data-anchor-id="essential-issues-must-be-addressed-paper-cannot-stand-as-is">Essential issues (must be addressed – paper cannot stand as-is)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 46%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Scientific justification</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E1</td>
<td>n_rep = 5 is below the recommended minimum of 20</td>
<td>R2</td>
<td>With 5 repetitions and K=2 folds (N=63), the median coefficient and adjusted SE variance component are estimated with effectively 4 degrees of freedom. Several specifications have p-values in the 0.03–0.20 range, so marginal significance conclusions are sensitive to cross-fitting noise. A single aberrant fold split could shift the median by 20–30%.</td>
<td>Re-run notebook 04 with n_rep = 20 (the config default). Update all downstream tables and figures if estimates change.</td>
</tr>
<tr class="even">
<td>E2</td>
<td>“Best” learner copies Forest result wholesale instead of combining best-outcome and best-treatment learners</td>
<td>R2</td>
<td>The paper states “Best learner (Forest for outcome, Lasso for treatment)” but the reported coefficient (0.018) and SE (0.0106) are identical to the Forest row in dml_results.json, confirming that the best-treatment learner (Lasso, which achieves higher treatment R-squared: 0.312 vs.&nbsp;0.286) was never used. The paper is factually misleading about what “Best” represents.</td>
<td>Fix the Best learner logic in notebook 04 to re-fit PLR using Forest for ml_l and Lasso for ml_m. Update dml_results.json, all DML tables, and the forest plot.</td>
</tr>
</tbody>
</table>
</section>
<section id="suggestions-would-improve-but-are-optional" class="level3">
<h3 class="anchored" data-anchor-id="suggestions-would-improve-but-are-optional">Suggestions (would improve but are optional)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 24%">
<col style="width: 37%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>S1</td>
<td>Estimand never formally defined – theta is a partial linear marginal effect, not an ATE</td>
<td>R1</td>
<td>Add a paragraph in Section 3.1 formally defining the estimand as the PLR coefficient theta (marginal effect of a one-unit increase in treatment holding X fixed). Clarify that GATE estimates are group-specific marginal effects, not ATEs from a binary intervention.</td>
</tr>
<tr class="even">
<td>S2</td>
<td>Low nuisance R-squared implications deserve deeper discussion</td>
<td>R1, R2</td>
<td>Add 2–3 sentences in Section 4 acknowledging that low R-squared_Y (0.094) means the ML learners may not effectively capture confounding structure, limiting the debiasing value of DML relative to OLS. Note B&amp;N validation mitigates but does not fully resolve this. R2 additionally suggests a nuisance R-squared table across all learners and panels.</td>
</tr>
<tr class="odd">
<td>S3</td>
<td>Ensemble SE computed as weighted average of individual SEs (invalid)</td>
<td>R2</td>
<td>Either compute the ensemble SE via the delta method with the stacking covariance matrix, or report the ensemble as a point estimate only with a footnote that no valid SE is available.</td>
</tr>
<tr class="even">
<td>S4</td>
<td>NeuralNet should be formally excluded or downweighted in interpretation</td>
<td>R2, R3</td>
<td>Move NeuralNet to a footnote or appendix given catastrophic R-squared (-38.8 to -44.3). Note explicitly that NeuralNet was excluded from Best consideration so readers do not wonder if it contaminates the preferred estimate.</td>
</tr>
<tr class="odd">
<td>S5</td>
<td>Cross-fitting stability not reported</td>
<td>R2, R3</td>
<td>Store per-repetition coefficients (via obj.all_coef) and report the range or standard deviation of the repetition-level estimates for each learner. This directly addresses the small-sample cross-fitting concern.</td>
</tr>
<tr class="even">
<td>S6</td>
<td>Report bivariate (no-controls) OLS coefficient alongside existing estimates</td>
<td>R1</td>
<td>A one-line regression that would clarify whether DML estimates are closer to the bivariate or controlled OLS, sharpening the interpretation of how much confounding ML nuisance models remove.</td>
</tr>
<tr class="odd">
<td>S7</td>
<td>Forest plot title has encoding artefact</td>
<td>R3</td>
<td>Fix the garbled arrow character in the forest plot title to use a plain ASCII arrow or Unicode right-arrow.</td>
</tr>
<tr class="even">
<td>S8</td>
<td>Replication table should clarify SE type</td>
<td>R3</td>
<td>Add a note to the replication table clarifying whether the slight SE differences between published and replicated values are due to SE type or rounding (e.g., “Published SEs as reported in the original; replicated SEs use HC1”).</td>
</tr>
<tr class="odd">
<td>S9</td>
<td>CLAN lacks statistical power – note more explicitly</td>
<td>R2</td>
<td>Add that with N=13 per extreme quintile, a standardised effect of d~1.1 would be needed for 80% power, making CLAN essentially uninformative.</td>
</tr>
<tr class="even">
<td>S10</td>
<td>BLP uses manual OLS rather than the DoubleML API</td>
<td>R2</td>
<td>The manual approach is methodologically valid but using obj_hte.blp() would reduce implementation risk. Consider switching for consistency.</td>
</tr>
<tr class="odd">
<td>S11</td>
<td>Discuss plausibility of selection-on-observables more explicitly</td>
<td>R1</td>
<td>Brief paragraph acknowledging main omitted-variable threats (institutional quality, trade openness beyond tariffs, colonial history).</td>
</tr>
<tr class="even">
<td>S12</td>
<td>Note that K=2 with N=63 leaves only ~32 observations per fold</td>
<td>R1</td>
<td>Mention this as a contributing factor to low nuisance R-squared.</td>
</tr>
</tbody>
</table>
</section>
<section id="blocking-issues-require-re-running-a-notebook" class="level3">
<h3 class="anchored" data-anchor-id="blocking-issues-require-re-running-a-notebook">Blocking issues (require re-running a notebook)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 5%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 30%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Issue</th>
<th>Raised by</th>
<th>Notebook to fix</th>
<th>Specific action</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E1</td>
<td>n_rep = 5 instead of 20</td>
<td>R2</td>
<td>04_dml_extension</td>
<td>Remove the n_rep override (line ~155) or set n_rep = 20. Re-execute notebook.</td>
</tr>
<tr class="even">
<td>E2</td>
<td>Best learner copies Forest wholesale</td>
<td>R2</td>
<td>04_dml_extension</td>
<td>Fix Best learner logic (line ~520) to instantiate a new DoubleMLPLR with ml_l = Forest and ml_m = Lasso, rather than copying all results from the best-outcome method. Re-execute notebook.</td>
</tr>
</tbody>
</table>
<p>RERUN_NEEDED: yes</p>
</section>
<section id="downgraded-items" class="level3">
<h3 class="anchored" data-anchor-id="downgraded-items">Downgraded items</h3>
<ul>
<li><strong>R1-Essential-2 (low nuisance R-squared implications understated) downgraded to S2.</strong> Referee 1 marked this essential, arguing that low R-squared means DML removes little confounding. While the scientific reasoning is sound, the paper already discusses nuisance R-squared in Section 4, correctly invokes Neyman orthogonality, and provides B&amp;N external validation. The paper is not uninterpretable or misleading without additional sentences – it would merely be more thorough. Adding 2–3 sentences of deeper discussion is a quality improvement, not a prerequisite for interpretability. Downgraded to suggestion per Berk et al.&nbsp;(2017) quality-control principles.</li>
</ul>
</section>
<section id="referee-disagreements" class="level3">
<h3 class="anchored" data-anchor-id="referee-disagreements">Referee disagreements</h3>
<p>No substantive disagreements. All three referees agree on: (i) the replication is successful, (ii) the DML extension adds value, (iii) the heterogeneity analysis is a genuine contribution, and (iv) the paper merits minor revision. The only difference is in severity: R1 and R2 each identify 2 essential issues while R3 identifies none. After synthesis, 2 essential issues remain (both from R2, both blocking), which is within the expected 0–3 range for a well-functioning review.</p>
</section>
<section id="already-resolved-suppressed-from-this-round" class="level3">
<h3 class="anchored" data-anchor-id="already-resolved-suppressed-from-this-round">Already resolved (suppressed from this round)</h3>
<p>None – this is Round 1 with no prior changelogs.</p>
</section>
</div>
<div id="tabset-1-9" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-9-tab">
<section id="final-review-report" class="level1">
<h1>Final Review Report</h1>
<p><strong>Paper:</strong> The Structure of Tariffs and Long-term Growth <strong>Original authors:</strong> Nunn, N. and Trefler, D. (<em>American Economic Journal: Macroeconomics</em>, 2010) <strong>Rounds completed:</strong> 1 of 3 <strong>Final verdict:</strong> Ready</p>
<hr>
</section>
</div>
<div id="tabset-1-10" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-10-tab">
<p>The DML extension with five learners (plus Ensemble and Best selector) shows that the original OLS estimate of the tariff skill-bias effect on growth is roughly twice the DML magnitude across all three treatment specifications. For the primary treatment (skill1_corr), the OLS coefficient is 0.035 (p = 0.004) while the DML Best (Boosting) estimate is 0.020 (p = 0.111) – positive but no longer significant at 5%. This pattern holds for all three treatments: DML estimates are 40–55% smaller than OLS and their 95% confidence intervals generally include zero, indicating that the tariff–growth relationship is not robust to flexible nonlinear controls. The heterogeneity analysis is the most valuable new contribution: the BLP test strongly rejects constant effects (beta2 = 1.099, p &lt; 0.001), and GATE estimates range from -0.206 (Q1) to +0.235 (Q5), revealing that skill-biased tariffs harm growth in some countries while benefiting others – a finding entirely absent from the original paper. The close agreement with Baiardi &amp; Naghi (2024) benchmarks (within 0.001–0.004 for all three Lasso specifications) provides strong external validation.</p>
<p><strong>“Would I be pleased to have written this, flaws and all?”</strong> Yes. The replication is essentially perfect, the DML extension produces a clear and policy-relevant qualification of the original finding (effect halved and no longer significant), the heterogeneity analysis adds genuine substance, and the remaining limitations (low nuisance R-squared, small sample) are inherent to the setting and honestly reported.</p>
<hr>
</div>
<div id="tabset-1-11" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-11-tab">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Specification</th>
<th>Published</th>
<th>Replicated</th>
<th>Delta (%)</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Panel A: skill1_corr</td>
<td>0.035</td>
<td>0.035</td>
<td>0.46%</td>
<td>PASS</td>
</tr>
<tr class="even">
<td>Panel B: diffa</td>
<td>0.016</td>
<td>0.016</td>
<td>1.64%</td>
<td>PASS</td>
</tr>
<tr class="odd">
<td>Panel C: diffg</td>
<td>0.020</td>
<td>0.019</td>
<td>5.11%</td>
<td>PASS*</td>
</tr>
</tbody>
</table>
<p>*Panel C marginally exceeds the 5% threshold (5.11%), but this is a rounding artefact: the raw replicated coefficient is 0.01898 and the published value 0.020 is itself rounded. Signs, significance levels, sample sizes (N = 63), and R-squared values (0.700–0.748) all match exactly.</p>
<p><strong>Overall:</strong> 3/3 specifications substantively replicated. The replication is an unambiguous success.</p>
<hr>
</div>
<div id="tabset-1-12" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-12-tab">
<section id="panel-a-skill1_corr-primary-treatment" class="level3">
<h3 class="anchored" data-anchor-id="panel-a-skill1_corr-primary-treatment">Panel A: skill1_corr (primary treatment)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>Coef</th>
<th>SE</th>
<th>95% CI</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS (original)</td>
<td>0.035</td>
<td>0.012</td>
<td>[0.011, 0.059]</td>
<td>0.004</td>
</tr>
<tr class="even">
<td>Best (Boosting/Boosting)</td>
<td>0.020</td>
<td>0.012</td>
<td>[-0.005, 0.044]</td>
<td>0.111</td>
</tr>
<tr class="odd">
<td>Ensemble</td>
<td>0.019</td>
<td>0.012</td>
<td>[-0.005, 0.043]</td>
<td>0.124</td>
</tr>
<tr class="even">
<td>Lasso</td>
<td>0.020</td>
<td>0.013</td>
<td>[-0.006, 0.046]</td>
<td>0.137</td>
</tr>
<tr class="odd">
<td>Boosting</td>
<td>0.020</td>
<td>0.012</td>
<td>[-0.005, 0.044]</td>
<td>0.111</td>
</tr>
<tr class="even">
<td>Forest</td>
<td>0.018</td>
<td>0.011</td>
<td>[-0.003, 0.038]</td>
<td>0.095</td>
</tr>
<tr class="odd">
<td>DecisionTree</td>
<td>0.013</td>
<td>0.011</td>
<td>[-0.009, 0.035]</td>
<td>0.237</td>
</tr>
<tr class="even">
<td>NeuralNet</td>
<td>0.267</td>
<td>0.099</td>
<td>[0.073, 0.461]</td>
<td>0.007</td>
</tr>
</tbody>
</table>
</section>
<section id="panel-b-diffa" class="level3">
<h3 class="anchored" data-anchor-id="panel-b-diffa">Panel B: diffa</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>Coef</th>
<th>SE</th>
<th>95% CI</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS (original)</td>
<td>0.016</td>
<td>0.006</td>
<td>[0.005, 0.028]</td>
<td>0.004</td>
</tr>
<tr class="even">
<td>Best (Boosting/Boosting)</td>
<td>0.011</td>
<td>0.006</td>
<td>[-0.001, 0.023]</td>
<td>0.064</td>
</tr>
</tbody>
</table>
</section>
<section id="panel-c-diffg" class="level3">
<h3 class="anchored" data-anchor-id="panel-c-diffg">Panel C: diffg</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Method</th>
<th>Coef</th>
<th>SE</th>
<th>95% CI</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS (original)</td>
<td>0.019</td>
<td>0.005</td>
<td>[0.009, 0.029]</td>
<td>&lt;0.001</td>
</tr>
<tr class="even">
<td>Best (Boosting/Boosting)</td>
<td>0.006</td>
<td>0.005</td>
<td>[-0.004, 0.017]</td>
<td>0.234</td>
</tr>
</tbody>
</table>
<p><strong>Key finding:</strong> DML estimates are consistently positive but 40–55% smaller than OLS across all three treatments. The Best learner (Boosting for both nuisance equations) yields Panel A: 0.020 (p = 0.111), Panel B: 0.011 (p = 0.064), Panel C: 0.006 (p = 0.234). Only Panel B approaches marginal significance. All five well-behaved learners agree on sign, but the 95% CIs generally include zero. The tariff–growth effect is directionally supported but not statistically robust to flexible nonlinear controls. This closely matches the Baiardi &amp; Naghi (2024) conclusion that OLS overstates the relationship in this small sample.</p>
<hr>
</section>
</div>
<div id="tabset-1-13" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-13-tab">
<p>The BLP test strongly rejects constant effects (beta2 = 1.099, p &lt; 0.001). GATE estimates by quintile of predicted CATE:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quintile</th>
<th>Coef</th>
<th>95% CI (jointly valid)</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Q1 (low)</td>
<td>-0.206</td>
<td>[-0.355, -0.057]</td>
<td>Significantly negative</td>
</tr>
<tr class="even">
<td>Q2</td>
<td>-0.022</td>
<td>[-0.049, 0.006]</td>
<td>Near zero</td>
</tr>
<tr class="odd">
<td>Q3</td>
<td>0.014</td>
<td>[-0.005, 0.033]</td>
<td>Near zero</td>
</tr>
<tr class="even">
<td>Q4</td>
<td>0.076</td>
<td>[0.042, 0.110]</td>
<td>Significantly positive</td>
</tr>
<tr class="odd">
<td>Q5 (high)</td>
<td>0.235</td>
<td>[0.097, 0.373]</td>
<td>Large positive</td>
</tr>
</tbody>
</table>
<p>The non-overlapping CIs between Q1 and Q4–Q5 confirm genuine heterogeneity. The CATE distribution has mean 0.008, SD 0.217, and range [-0.469, 0.456]. CLAN is uninformative (N = 13 per extreme quintile; only s_w_asia reaches p &lt; 0.05, likely spurious given 17 tests).</p>
<hr>
</div>
<div id="tabset-1-14" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-14-tab">
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 31%">
<col style="width: 20%">
<col style="width: 22%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Issue</th>
<th>Raised (round)</th>
<th>Category</th>
<th>Resolved?</th>
<th>How</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>E1: n_rep = 5 instead of 20</td>
<td>R1 (Ref 2)</td>
<td>Essential</td>
<td>Yes</td>
<td>Removed hardcoded override; re-ran with n_rep = 20 from config</td>
</tr>
<tr class="even">
<td>E2: Best learner copied Forest wholesale</td>
<td>R1 (Ref 2)</td>
<td>Essential</td>
<td>Yes</td>
<td>Fixed Best logic to combine best-outcome and best-treatment learners; after re-run, Boosting won both, so Best = Boosting (no longer identical to Forest)</td>
</tr>
<tr class="odd">
<td>S1: Estimand not formally defined</td>
<td>R1 (Ref 1)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Added paragraph in Section 3.1 defining theta as PLR marginal effect</td>
</tr>
<tr class="even">
<td>S2: Nuisance R-squared discussion too thin</td>
<td>R1 (Refs 1, 2)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Added sentences in Section 4 on debiasing limitations at low R-squared</td>
</tr>
<tr class="odd">
<td>S4: NeuralNet not explicitly excluded</td>
<td>R1 (Refs 2, 3)</td>
<td>Suggestion</td>
<td>Addressed</td>
<td>Added sentence and footnote in Section 3.1</td>
</tr>
<tr class="even">
<td>S3: Ensemble SE invalid</td>
<td>R1 (Ref 2)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Non-trivial; Ensemble is not the preferred estimator</td>
</tr>
<tr class="odd">
<td>S5: Cross-fitting stability not reported</td>
<td>R1 (Refs 2, 3)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Per-rep coefs stored in JSON but not surfaced in paper tables</td>
</tr>
<tr class="even">
<td>S6: Bivariate OLS for comparison</td>
<td>R1 (Ref 1)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Would require new regression</td>
</tr>
<tr class="odd">
<td>S7: Forest plot title encoding</td>
<td>R1 (Ref 3)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Minor rendering issue</td>
</tr>
<tr class="even">
<td>S8: Replication SE type clarification</td>
<td>R1 (Ref 3)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Minor table footnote</td>
</tr>
<tr class="odd">
<td>S9: CLAN power note</td>
<td>R1 (Ref 2)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Already noted as underpowered</td>
</tr>
<tr class="even">
<td>S10: BLP via DoubleML API</td>
<td>R1 (Ref 2)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Manual implementation is valid</td>
</tr>
<tr class="odd">
<td>S11: Selection-on-observables discussion</td>
<td>R1 (Ref 1)</td>
<td>Suggestion</td>
<td>Deferred</td>
<td>Original paper already frames this</td>
</tr>
<tr class="even">
<td>S12: K=2 fold size note</td>
<td>R1 (Ref 1)</td>
<td>Suggestion</td>
<td>Addressed (implicitly)</td>
<td>Folded into S2 discussion mentioning ~32 obs per fold</td>
</tr>
</tbody>
</table>
<hr>
</div>
<div id="tabset-1-15" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-15-tab">
<p>No essential issues remain. The paper is ready to share. The suggestions below would strengthen it further but are optional.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 29%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Item</th>
<th>Category</th>
<th>Action needed</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Ensemble SE reported as weighted average of individual SEs (technically invalid)</td>
<td>Suggestion</td>
<td>Either implement delta-method SE or add a footnote that Ensemble CI should be interpreted with caution</td>
</tr>
<tr class="even">
<td>2</td>
<td>Cross-fitting stability not shown in the paper</td>
<td>Suggestion</td>
<td>Surface per-rep coefficient ranges from dml_results.json in a table or footnote</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Bivariate (no-controls) OLS not reported</td>
<td>Suggestion</td>
<td>One-line regression to show whether DML is closer to bivariate or controlled OLS</td>
</tr>
<tr class="even">
<td>4</td>
<td>Forest plot title has encoding artefact</td>
<td>Suggestion</td>
<td>Fix garbled arrow character in title</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Replication table does not clarify SE type</td>
<td>Suggestion</td>
<td>Add footnote on published vs.&nbsp;replicated SE methodology</td>
</tr>
<tr class="even">
<td>6</td>
<td>CLAN power calculation not explicit</td>
<td>Suggestion</td>
<td>Note that d ~ 1.1 needed for 80% power with N = 13 per group</td>
</tr>
</tbody>
</table>
<p><em>Category: <strong>Essential</strong> = must fix before sharing. <strong>Suggestion</strong> = would improve, optional.</em></p>
<hr>
</div>
<div id="tabset-1-16" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-16-tab">
<ul>
<li><p><strong>The RECAST qualifies the original finding.</strong> The positive tariff–growth effect survives directionally (all well-behaved DML learners agree on sign), but the magnitude is halved and statistical significance is lost. This is a “weaker support” verdict, not an overturning. The heterogeneity analysis adds a genuinely new dimension: the average effect masks a gradient from significantly negative (Q1: -0.206) to significantly positive (Q5: +0.235).</p></li>
<li><p><strong>The small sample (N = 63) is the binding constraint.</strong> With 17 controls and 2-fold cross-fitting, each fold has only ~32 observations for training flexible ML models. This limits nuisance R-squared (best: 0.154 for outcome, 0.362 for treatment), inflates standard errors, and makes CLAN uninformative. These are inherent features of the data, not pipeline failures. The Baiardi &amp; Naghi (2024) replication faces identical constraints.</p></li>
<li><p><strong>External validation is strong.</strong> Our Lasso estimates match B&amp;N (2024) benchmarks within 0.001–0.002 for all three treatments (our 0.020 vs.&nbsp;their 0.019 for Panel A; our 0.008 vs.&nbsp;their 0.010 for Panel B; our 0.006 vs.&nbsp;their 0.009 for Panel C). This is the strongest evidence that the pipeline is working correctly despite low nuisance R-squared.</p></li>
<li><p><strong>The pipeline cannot verify causal identification.</strong> The original paper’s claim rests on selection-on-observables with 17 controls. Whether these controls are sufficient to close all backdoor paths (e.g., institutional quality, trade openness beyond tariffs, colonial history beyond regional dummies) is a substantive judgment that no automated pipeline can make. DML relaxes functional-form assumptions but not the unconfoundedness assumption.</p></li>
<li><p><strong>After the revision, Boosting is the Best learner for both nuisance equations across all three panels.</strong> This resolved the Round 1 issue where Best was incorrectly copying Forest results. In the corrected run, Boosting achieves the lowest nuisance MSE for both outcome (R-squared = 0.154) and treatment (R-squared = 0.362), so Best = Boosting throughout. The Best coefficients are no longer identical to the Forest row, confirming the fix worked.</p></li>
</ul>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/qgallea\.github\.io\/recast-causal-ai");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p><strong>RECAST</strong> by <a href="https://thecausalmindset.com">Quentin Gallea, Ph.D.</a> · Built with <a href="https://claude.ai/code">Claude Code</a> &amp; <a href="https://quarto.org">Quarto</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/qgallea/recast-causal-ai/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p><a href="https://github.com/qgallea/recast-causal-ai">GitHub</a> · <a href="https://thecausalmindset.com/training/claude-code-for-research">Claude Code for Research</a></p>
</div>
  </div>
</footer>




</body></html>